### ISSUE TITLE
New Refactoring: Toggle async function

### ISSUE THREAD

**Issue by Chandler-Davidson** [nicoespeon/abracadabra#100]
# Toggle Async Function
## Description
When writing in Typescript, I often forget to mark my functions as `async `and then forget the update its return type to `Promise<T>`. I would love a refactor feature that could flip my function between sync and async.

## Example
Existing code:
```typescript
function makeRequest(): string {
  const resp = await fetch('http://github.com')
  return await resp.json();
}
```

After running refactor:
```typescript
async function makeRequest(): Promise<string> {
  const resp = await fetch('http://github.com')
  return await resp.json();
}
```

**Comment by nicoespeon** [comment]
Hi @Chandler-Davidson 👋 

Thanks for suggesting! 
However, you can already do that today if you put your cursor on the `await` keyword:

![CleanShot 2020-04-14 at 07 15 09](https://user-images.githubusercontent.com/1094774/79219172-c1e02680-7e1f-11ea-8666-eab172a62e51.gif)

It's provided by TypeScript directly.

_N.B: here I clicked on the lightbulb, but if you have Abracadabra then you should be able to just click <kbd>Alt</kbd> <kbd>Enter</kbd>._

**Comment by fabien0102** [comment]
Just saying, remove the manual output type from the function definition, and everything is following automatically 🙄
