### ISSUE TITLE
New refactoring: Simplify boolean logic

### ISSUE THREAD

**Issue by ipanasenko** [nicoespeon/abracadabra#1041]
## Is this request related to a problem? Please describe.

Sometimes during refactors I'm ending up with boolean literals inside logical expressions.
I've just switched from WebStorm to VS Code and I miss WS refactor feature to simplify these kinds of expressions.

## Describe the solution you'd like

Similar to "simplify ternary", I'd like this refactoring to simplify boolean logic.
Examples:
`true || somethingElse` => `true` (after this can be cleaned up with dead code elimination refactoring or simplify ternary)
`somethingElse || true` => `true` (same as above, different operands order)
`true && somethingElse` => `somethingElse`
`false || somethingElse` => `somethingElse`
`false && somethingElse` => `false`
`!true && somethingElse` => `false`
`somethingElse && true && anotherOne` => `somethingElse && anotherOne`

## Additional context

![image](https://github.com/user-attachments/assets/180f4745-b8bc-44ff-98a7-499a9ddee01d)
![image](https://github.com/user-attachments/assets/7ec534cd-d78b-4a38-a7e9-213875a24827)
![image](https://github.com/user-attachments/assets/f2727c9d-5f84-418d-873e-3678274bb757)

Thanks!

**Comment by nicoespeon** [comment]
Sounds like a great idea @ipanasenko 👍 

Is it something you'd like to work on? Otherwise, I will try to do that some time in August.

**Comment by ipanasenko** [comment]
I might try, but it will take me longer due to lack of experience with extensions + taking vacation soon :)
I will update if I'm able to produce something meaningful, but if you are faster than me - that's also okay :)

**Comment by nicoespeon** [comment]
Good to know. I may have some time on Saturday to give it a go, I'll let you know 😉

**Comment by nicoespeon** [comment]
@ipanasenko got it to work!

I'll get a new release out of the door. Let me know if you find use-cases that are not covered yet, I'll iterate on that 😉

https://github.com/user-attachments/assets/68d5d66f-81ca-464f-9048-d170780afee2

**Comment by nicoespeon** [comment]
@all-contributors please add ipanasenko for ideas

**Comment by ipanasenko** [comment]
I've updated to 9.4.0, but it seems broken 😬
I don't see any action on Alt+Enter, and from command pallette I get an error:
<img width="278" alt="image" src="https://github.com/user-attachments/assets/2087f2e5-ec4b-4592-81eb-b9676756c843">
Tried uninstall-reinstall, restart VSCode - doesn't help.
9.3.0 works just fine

**Comment by nicoespeon** [comment]
@ipanasenko thank you. Something went wrong with 9.4.0 indeed. v9.4.1 seems to have fixed it for me. Could you try to upgrade and let me know if it works for you too?

It seems that the issue was with the upgrade of esbuild from 0.19 to 0.22 (https://github.com/nicoespeon/abracadabra/pull/1032). I should have been more careful about this because it only manifests when you package the extension.

Hopefully, it seems that they reverted the problematic changes with 0.23: https://github.com/evanw/esbuild/blob/main/CHANGELOG.md#0230

But I'm waiting for other people to confirm the fix is working before closing this issue.

**Comment by ipanasenko** [comment]
9.4.1 works! 👍
