### ISSUE TITLE
Tabs replaced by single space when applying refactoring

### ISSUE THREAD

**Issue by jrnail23** [nicoespeon/abracadabra#105]
## Describe the bug

My team uses tabs to format our code, but when I use Abracadabra to refactor, it reformats my whole file, replacing each tab with a single space.  I then have to reformat it myself to get my tabs back (luckily prettier is there to help).

BTW, this seems to only happen on some refactorings.  "Inline" doesn't do it, but things like "Move Statement Up/Down", "Add/Remove Braces from Arrow Function", and "Remove Redundant Else" all do cause it to happen.

## Additional information

- Version of the extension impacted: 4.2.0

**Comment by nicoespeon** [comment]
Thanks for the test reproducing the error 👍 

Will have a look at that. We're using recast so it should be able to detect current indentation to preserve that when it creates new nodes 🤔

**Comment by jrnail23** [comment]
@nicoespeon, when digging through the code I found that recast has a `useTabs` option.  I figure you could try to detect tabs or maybe provide a setting for the extension.
