### ISSUE TITLE
Convert a `let` to `const` for a variable declaration where the context allows it

### ISSUE THREAD

**Issue by nickebbitt** [nicoespeon/abracadabra#107]
## Is this request related to a problem? Please describe.

Favouring immutability, it would be good to have a quick fix to convert a variable declaration from `let` to `const` if the scope and usage of the variable allows it.

## Describe the solution you'd like

Given the following code:
```
function getValue(): string {
   let someVariable = 'value';
   return someVariable;
}
```
A quick-fix on `someVariable` would allow conversion to this:
```
function getValue(): string {
   const someVariable = 'value';
   return someVariable;
}
```
Whereas it wouldn't be available for:
```
function getValue(): string {
   let someVariable = 'value';
   someVariable = 'anotherValue';
   return someVariable;
}
```

**Comment by nicoespeon** [comment]
This would be a nice feature. Obviously, the tricky part of it is to detect usages of the identifier in scope to detect whether or not it's re-assigned.

The transformation part is quite easy to implement.

I'll mark it as a good first issue. I can provide guidance on a draft PR if one needs.

**Comment by nickebbitt** [comment]
Should we also look to handle `var` for this feature? Seems like it makes sense.

**Comment by nicoespeon** [comment]
`var` is trickier because of the scope, but yeah it would make sense!

I wouldn't mind starting with let / const and iterate to handle var later on.

**Comment by chemitaxis** [comment]
I can do it, can you please explain a little about how to solve? Thanks!

**Comment by nickebbitt** [comment]
Hey @chemitaxis, sorry if it wasn't obvious but I've started work on this. I wouldn't want this to stop you though contributing though.

Maybe @nicoespeon has another issue in mind that would be a good one to get started on?

**Comment by nickebbitt** [comment]
@chemitaxis a great place to start anyway is to work through the [contributing guide](https://github.com/nicoespeon/abracadabra/blob/master/CONTRIBUTING.md).

**Comment by nicoespeon** [comment]
Shipped in a brand new release ✨
