### ISSUE TITLE
Provide a way to hide quick fixes

### ISSUE THREAD

**Issue by OliverJAsh** [nicoespeon/abracadabra#112]
## Is this request related to a problem? Please describe.

There are some quick fixes which I will never use, for example "convert let to const" and "split declaration and initialization". It is annoying that these add noise to the quick fixes menu, especially when VS Code are other extensions and contributing many other quick fixes.

## Describe the solution you'd like

I would like to be able to hide some of the refactorings from appearing in the quick fixes menu. Perhaps a setting for each refactoring?

## Additional context

Also mentioned here: https://github.com/nicoespeon/abracadabra/issues/95#issuecomment-612056144-permalink:~:text=it%20would%20be%20OK%20to%20propose,prefer%20to%20use%20the%20shortcut%20only

Going further, it would be great to be able to add refactorings to the quick fix menu which don't appear there by default. This would help with discoverability. I'm very unlikely to discover/remember a refactoring if it's not in the menu, although at some point it will become more natural and at that point I would like to hide it from appearing in the quick fix menu. Related: https://github.com/nicoespeon/abracadabra/issues/95

**Comment by OliverJAsh** [comment]
Actually this might be something for VS Code https://github.com/microsoft/vscode/issues/101129

**Comment by nicoespeon** [comment]
We could provide a boolean for each refactoring key to enable/disable them from appearing in CodeActionProviders.

We should be able to filter this list, based on the config: https://github.com/nicoespeon/abracadabra/blob/9683cbaa2a21761c184142470be2473e9be106a9/src/action-providers.ts#L16

Doing so, we should provide Quick Fixes for all refactorings, including the ones that don't have it today. This will help discoverability & allow for experienced users to disable them to reduce noise.

We should be able to update docs to:
- tell it's possible to disable the Quick Fix & still execute the refactoring
- stop saying "available as quick fix" for all individual refactorings
