### ISSUE TITLE
Emojis in code fixes menu hurt accessibility

### ISSUE THREAD

**Issue by OliverJAsh** [nicoespeon/abracadabra#117]
## Describe the bug

_A clear and concise description of what the bug is._

## How to reproduce

1. Open a code fix menu with multiple suggestions, e..g 
2. Type a letter

![image](https://user-images.githubusercontent.com/921609/86133382-1ff7de00-bae0-11ea-9f47-4568c2938d44.png)

## Expected behavior

Focus should move to the first entry beginning with that letter. In this case, if we type "a", it should focus "Add braces to arrow function".

This doesn't happen because all of the menu items begin with an emoji rather than a letter.

## Screenshots

See above.

## Additional information

This is standard OS behaviour for filtering dropdown menus.

**Comment by nicoespeon** [comment]
TIL you could do that! Thank you @OliverJAsh 👍 

I put the emoji at the end. FYI, I use an emoji so it's easy to distinct Abracadabra Quick Fixes vs. others that could eventually be provided by other extensions (I used to have others installed and the emojis were handy).
