### ISSUE TITLE
Upgrade Recast and other dependencies to fix bugs

### ISSUE THREAD

**Issue by OliverJAsh** [nicoespeon/abracadabra#120]
I ran into a bug that happened to be due to Recast. It's fixed in a newer version.

https://github.com/facebook/jscodeshift/issues/330
https://github.com/benjamn/recast/pull/613

It might also be worth upgrading other dependencies. I'm still running into that `export default` bug 😒 .

I had a go at doing it myself but ran into loads of type errors which I'm not sure how to fix.

**Comment by nicoespeon** [comment]
Sure thing. I just installed dependabot to start keeping the dependencies up-to-date. 

Of course, some upgrades might break code and we'll have to adapt to the breaking changes to make it work. But we can totally do 👍

**Comment by nicoespeon** [comment]
This has been fixed by #122 (thank you Dependabot!)

There were no failing test, everything looks good on master 👍
