### ISSUE TITLE
Split into multiple declarations

### ISSUE THREAD

**Issue by nicoespeon** [nicoespeon/abracadabra#130]
## Is this request related to a problem? Please describe.

It can happen to have many declarations made together, and we may want to split them so we can treat them individually.

## Describe the solution you'd like

```js
const firstName = "Jane", lastName = "Doe";
```

Should become

```js
const firstName = "Jane";
const lastName = "Doe";
```

Same for `var` and `let` keywords.

Beware of preserving types for TS.

## Additional context

This seems to be an easy refactoring to do: convert an existing Variable Declarator into multiple ones, one per declaration.

**Comment by iulspop** [comment]
Can I be assigned to complete this issue?

**Comment by nicoespeon** [comment]
Sure @iulspop, there you go 👍 

If you need help, we can pair a bit on this.

**Comment by iulspop** [comment]
@nicoespeon for sure I'd like to pair! I'll send you a message on software crafters slack.
