### ISSUE TITLE
[Convert to arrow function] Detect when function is called before declaration

### ISSUE THREAD

**Issue by nicoespeon** [nicoespeon/abracadabra#155]
## Describe the bug

Function declaration are not hoisted, so conversion can generate broken code.

## How to reproduce

```ts
doSomething();

function doSomething() {}
```

Convert `doSomething()` to arrow function produces:

```ts
doSomething();

const doSomething = () => {};
```

Which is invalid.

## Expected behavior

Either:
- Don't do the refactoring and show an error explaining what needs to be fixed first

**Comment by David-Else** [comment]
I see you are 'tracking edge cases' here:

Convert to Arrow Function does not appear as an option when there is an `export` statement in front of the function. Maybe check that out too, cheers.

**Comment by David-Else** [comment]
`app.tsx`
```
import React, { MouseEvent } from "react";

function App() {
  const startTrivia = async () => {};
  const checkAnswer = (e: React.MouseEvent<HTMLButtonElement>) => {};
  function nextQuestion() {}
  return <div className="App">iQuiz</div>;
}

export default App;
```
Try to convert `function nextQuestion() {}` to arrow function and it says `I'm sorry, I can't convert this function declaration, it's used before 😅`

**Comment by nicoespeon** [comment]
@David-Else aha, an interesting one.

I'm re-opening this issue to track the fix, thank you 👍

**Comment by nicoespeon** [comment]
OK, I found a repro in the following case:

```ts
import {Input} from "./types";

function checkAnswer(input: Input) {}

function doNothing() {}
```

The presence of the imported type in the previous function parameters make it impossible to convert `doNothing()`. I didn't pay attention to TS types much, there's likely a conflict. I'll create a test case for this.

**Comment by nicoespeon** [comment]
@David-Else found the issue. This was a weird edge case were imported types would count as references to the function declaration.

I added a test and fixed this by omitting these—it was not so hard, just filter out references that aren't actually a `FunctionDeclaration`.

This will be shipped today or tomorrow 👍 
Thank you for reporting ❤️
