### ISSUE TITLE
Reuse existing destructuring assignments when extracting member expressions

### ISSUE THREAD

**Issue by sluukkonen** [nicoespeon/abracadabra#162]
Given

```javascript
function test(obj) {
  return obj.x + obj.y * obj.x + obj.y
}
```

`obj.x` and `obj.y` are repeated, so let's extract both of them, replacing all occurrences. The end result is as follows.

```javascript
function test(obj) {
  const { x } = obj
  const { y } = obj
  return x + y * x + y
}
```

The second extraction could have reused the destructuring assignment that the first extraction created, making the code one line shorter.

```javascript
function test(obj) {
  const { x, y } = obj
  return x + y * x + y
}
```

- Version of the extension used: _v4.7.0_

**Comment by nicoespeon** [comment]
Agree, I don't see any reason not to do that 👍

**Comment by nicoespeon** [comment]
@all-contributors please add @sluukkonen for ideas

**Comment by nicoespeon** [comment]
@sluukkonen thanks for the suggestion. This is working now. I'll get it shipped by the end of the week 👍
