### ISSUE TITLE
Abracadabra is not available in VSCodium

### ISSUE THREAD

**Issue by NolwennD** [nicoespeon/abracadabra#163]
Hello,

I’m on Ubuntu with VSCodium from the official repo (https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs) and I can’t find Abracadabra in the marketplace. Did you know why?

**Comment by nicoespeon** [comment]
Hi @NolwennD 👋 

That's a good question, I didn't know about VSCodium until now! I'm not sure what needs to be done to publish the package here. I guess it's a matter of pushing the binary somewhere 🤔 

Do you know where I can find docs that would explain how to publish a package here? 

Also, for some reason, I can't access this page: https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs/
It's a 404 for me, even when I'm connected to my Gitlab account 🤷‍♂️

**Comment by NolwennD** [comment]
Sorry for the bad url, I extract it from the installation guide (https://vscodium.com/#install then scroll to debian/ubuntu).

**Comment by nicoespeon** [comment]
Thank you 👍 

It looks like there's something to do with https://open-vsx.org/

A vsx is generated during the build process. So I can probably figure out how to make it publish to this registry too, and that should make the extension appears on this Marketplace too.

I'll let you know about that. Thanks for raising it up, really helpful 😃

**Comment by nicoespeon** [comment]
Some news here: @fabien0102 and I have automated the releases to VS Code with a GitHub action.

Next step is to create a token on Open VSX and create a similar action to publish here too. Should be quite easy to do, I'd expect next release to be available on VS Codium.

**Comment by nicoespeon** [comment]
Hi @NolwennD 👋 

I'm glad to tell you that Abracadabra was published on Open VSX: https://open-vsx.org/extension/nicoespeon/abracadabra
Therefore, it should now be available on VS Codium.

Thank you for giving me the opportunity to automate the release process, and to make me discover Open VSX/VS Codium.

**Comment by NolwennD** [comment]
Hi @nicoespeon 

Good news, now you can hack Abracadabra with Gitpod and Abracadabra : https://gitpod.io/#https://github.com/nicoespeon/abracadabra/ . So recursive !
