### ISSUE TITLE
Do you noticed performance issue? Let us know.

### ISSUE THREAD

**Issue by nicoespeon** [nicoespeon/abracadabra#18]
I think the way we provide the Quick Fixes might lead to performance issues. So far, it seems to be fine. But I'm not sure how much current implementation will scale.

**If you experienced performance issues because of the extension, please let us know here 🙏**

## Details

Today, each Quick Fix is independent. 

To tell VS Code if it should propose a refactoring as a Quick Fix, we traverse the code, check if the refactoring could be made from current selection, and tell VS Code if we can.

Example of such behavior, implemented in `action-provider.ts`:

https://github.com/nicoespeon/abracadabra/blob/28273cf7eddae39b1db8473502fbcfe2cbe6cd73/src/refactorings/convert-ternary-to-if-else/action-provider.ts#L15-L35

https://github.com/nicoespeon/abracadabra/blob/28273cf7eddae39b1db8473502fbcfe2cbe6cd73/src/refactorings/convert-ternary-to-if-else/convert-ternary-to-if-else.ts#L27-L29

The performance problem would be due to the fact that **each refactoring parses, traverses and transforms the AST**. At some point, this could be too much. 

If this is confirmed, the solution would be to traverse the AST less. Ideally, we would traverse it once and try to figure out what list of refactorings could be performed from that.

The challenge would be to provide individual action providers to VS Code. That's why current implementation is very naive, so every refactoring is independent—*which simplifies development a lot!*

---

**But until we got actual confirmation that this is a concern, we'll keep current implementation.** #makeItWork #makeItRight #makeItFast

![hack-tv](https://user-images.githubusercontent.com/1094774/61837436-c65c4d80-ae52-11e9-8fb6-7bb88d9f1729.gif)

**Comment by simonhoss** [comment]
Hi. I have the case when I switch between different files. That it takes a long time until it shows the git changes (the blue marker on the left) and when I have wallaby activated it takes also some time until the rectangles on the side occurs

**Comment by nicoespeon** [comment]
Hi @simonhoss 👋 

I'm not sure what you mentioned is related to the Abracadabra extension. Wallaby takes also some time to boot indeed, but that's on Wallaby 👐 

I'll run perf analysis and come up with improvements for the extension if I find any issue. Overall, on my machine, despite working on big files I find Abracadabra to still have decent perfs today. However, I can already think about some improvements that would make it more scalable (e.g. we can add more refactorings without impacting the overall extension perfs).

**Comment by nicoespeon** [comment]
I'll finally start working on analyzing & improving the performances (if necessary). The idea is to make it fast & scalable, so we can add new refactorings without being concerned with perfs.

Closing the issue as I don't need more inputs on this 👌

**Comment by simonhoss** [comment]
Ok. If you need someone to test then tell me. Also I can share you a video how it behaves at the moment.
