### ISSUE TITLE
Extract variable produces invalid code

### ISSUE THREAD

**Issue by ajanian** [nicoespeon/abracadabra#192]
## Describe the bug

I have a scenario (the first one I tried with the plugin) where the extract refactoring produces invalid code.

## How to reproduce

```
function venueBtnName() {
  if (window.location.href.includes('raw')) {
    document.getElementById('venueExampleBtn').innerHTML = 'Venue Examples';
  } else {
    document.getElementById('venueExampleBtn').innerHTML = 'Venue Group Details';
  }
}
```

1. Highlight "document.getElementById('venueExampleBtn')"
2. press option+command+V
3. select "replace all 2 occurrences" from the command palette
4. That generates the following code:

```
function venueBtnName() {
  if (window.location.href.includes('raw')) const extracted = document.getElementById('venueExampleBtn');
                                            {
    extracted.innerHTML = 'Venue Examples';
  } else {
    extracted.innerHTML = 'Venue Group Details';
  }
}
```

## Expected behavior

I would expect the generated code to look like:
```
function venueBtnName() {
  if (window.location.href.includes('raw')) {
    const extracted = document.getElementById('venueExampleBtn');
    extracted.innerHTML = 'Venue Examples';
  } else {
    extracted.innerHTML = 'Venue Group Details';
  }
}
```

## Screenshots

<img width="850" alt="image" src="https://user-images.githubusercontent.com/99716/99309772-f5f14f00-2827-11eb-90a9-17a6f645cdbe.png">

## Additional information

- Version of the extension impacted: _v4.9.3_

_🧙‍ Add any other context about the problem here._

**Comment by nicoespeon** [comment]
Thanks @ajanian for the very detailed bug report. That was super helpful to fix the issue.

So it turned out the logic of finding the parent scope wasn't correct when there was a block statement. I'm surprised we didn't catch the issue earlier. Nevermind, this is now resolved. I'll release a new version right now with the fix (+ what's in the changelog).

@allcontributor please add ajanian for bugs

**Comment by nicoespeon** [comment]
@all-contributors please add ajanian for bugs
