### ISSUE TITLE
Convert to arrow function converts the outermost function in scope

### ISSUE THREAD

**Issue by sluukkonen** [nicoespeon/abracadabra#196]
## Describe the bug

Consider the following code:

```typescript
function outer() {
  function inner() {
    return null
  }
}
```

## How to reproduce

If I use "Convert to arrow function on `inner`, `outer` is converted instead.

```typescript
const outer = () => {
  function inner() {
    return null
  }
}
```

## Expected behavior

I would expect abracadabra to convert the function under the cursor.

## Additional information

- Version of the extension impacted: _v4.11.0_

**Comment by nicoespeon** [comment]
Oh thanks for reporting, that's very true and very annoying. Hopefully, it was also easy to fix (we do that for most refactorings, this one was forgotten it seems).
