### ISSUE TITLE
Extract type

### ISSUE THREAD

**Issue by fabien0102** [nicoespeon/abracadabra#207]
## Is this request related to a problem? Please describe.

For now we have extract variable/interface/class, this is great, but we missed `Extract type`. Indeed, I found myself often starting by an inline type and extract them after, when I need to use this type in other part of the codebase.

## Describe the solution you'd like

With the following snippet:

```tsx
import React from "react";

export const MyComponent = (props: { name: string; age: number }) => (
  <div>
    {props.name} is {props.age} years old.
  </div>
);
```

I would like to be able to put my cursor inside the inline type (`{ name: string; age: number }`) and ask for `Extract type`

```tsx
import React from "react";

interface MyProps { // Cursor on here, with `MyProps` in rename mode
  name: string;
  age: number;
}

export const MyComponent = (props: MyProps) => (
  <div>
    {props.name} is {props.age} years old.
  </div>
);
```

## Additional context

I would of course love to have `interface` when this is possible and `type` when not.

As example:

```tsx
import React from "react";

interface MyProps {
  name: string;
  age: number;
}

export const MyComponent = (props: MyProps & { sexe: "male" | "female" }) => (
  <div>
    {props.name} is {props.age} years old.
  </div>
);
```

Should result as:

```tsx
import React from "react";

interface MyProps {
  name: string;
  age: number;
}

type ExtractedType = MyProps & { sexe: "male" | "female" } // Cursor here, with `ExtractedType` ready to be renamed

export const MyComponent = (props: ExtractedType) => (
  <div>
    {props.name} is {props.age} years old.
  </div>
);
```

**Comment by nicoespeon** [comment]
🎁

![2021-03-04 Screenshot-MgMXp0yN](https://user-images.githubusercontent.com/1094774/110062404-31f8e300-7d37-11eb-8302-182a7866d898.gif)
