### ISSUE TITLE
Split declaration and initialization duplicates type in ts declarations

### ISSUE THREAD

**Issue by iulspop** [nicoespeon/abracadabra#232]
## Describe the bug

For variable declarations in Typescript, type annotations are duplicated by the "split declaration and initialization" refactoring.

## How to reproduce

1. Initial code:
```ts
let index: number = 0;
```

2.  Apply "split declaration and initialization" refactoring.

3. Output:
```ts
let index: number;
index: number = 0;
```

## Expected behavior

Should be only one type annotation:
```ts
let index: number;
index = 0;
```

## Investigation & Solution
The AST hierarchy for type annotations looks like this:
```js
{
  type: 'VariableDeclaration',
  declarations: [
    {
      type: 'VariableDeclarator',
      id: {
        type: 'Identifier',
        typeAnnotation: { // <= Shouldn't be copied
          type: 'TSTypeAnnotation',
          typeAnnotation: 'TSNumberKeyword'
        }
      }
    }
  ]
}
```

The `typeAnnotation` field on the `Identifier` node is important.

When an `ExpressionStatement` node is created with the `Identifier` copied from the declaration, the `typeAnnotation` field on `Identifier` should not be copied too.

Note that for `Identifiers` without annotation, the `typeAnnotation` field is not set to `undefined`, but is undeclared. So, the `typeAnnotation` field shouldn't be set to `undefined` when copied, but deleted instead.

A possible solution is to delete the `typeAnnotation` field after the Identifier node is copied.

## Additional information

- Version of the extension impacted: 4.13.1

- Note that the AST explorer doesn't support Typescript, so to look at the ASL for Typescript code I made a set up like this:
```js
import parser from "@babel/parser";

const code = `let index: number = 0;`;

const ast = parser.parse(code, {
  plugins: ["typescript"]
});

console.log(ast.program.body[0].declarations[0].id)
```

**Comment by iulspop** [comment]
Is suspect this is an easy fix. Can I be assigned to fix this bug?

**Comment by nicoespeon** [comment]
@iulspop sure, go for it!
