### ISSUE TITLE
Toggle Braces: handle `for` loops & `while`

### ISSUE THREAD

**Issue by detzt** [nicoespeon/abracadabra#247]
## Is this request related to a problem? Please describe.

There exist refactorings to add or remove braces for if/else or arrow functions, but not for single line loops (`for`, `while`, ...).

## Describe the solution you'd like

Behaving exactly as for if/else, I would like refactorings to add or remove braces from single line loops.

## Additional context

I don't know about your internals, but maybe it would make sense to group all add/remove braces refactorings as a general refactoring that is applicable wherever braces can be added or removed.

**Comment by nicoespeon** [comment]
Hey @detzt 👋 

Actually, that's a great idea! I think we can merge this suggestion with https://github.com/nicoespeon/abracadabra/issues/211. The idea would be to consolidate what we have so we expose "toggle braces" on the closest statement. Then we would add more statements, like `for` loops, `while`, etc.

I'm closing this issue to merge with the other suggestion.

**Comment by nicoespeon** [comment]
Re-opening now that "Toggle Braces" was implemented.
