### ISSUE TITLE
When adding braces to arrow, store return value in intermediate

### ISSUE THREAD

**Issue by wmertens** [nicoespeon/abracadabra#273]
## Is this request related to a problem? Please describe.

I'm always frustrated when I add braces to an arrow function and I need to remove the newly added `return`, replacing it with `const out =`, then going to the closing brace and adding `return out`.

The reason is that when adding braces to an arrow function, it's almost always to do something with the value before it's returned.

## Describe the solution you'd like

1. run "add braces"
2. `() => foo` is replaced with
   ```js
    () => {
      const out = foo
      return out
    }
    ```
3. The `out` is selected and the variable rename wizard is run, like when you're moving a function to a constant in the module

## Additional context

Perhaps 3. isn't necesarry, and instead #211 could toggle between "no braces", "braces + const + return", "braces + return". Typing F2 isn't hard.

**Comment by nicoespeon** [comment]
That's an interesting use-case @wmertens, thanks for sharing.

> I need to remove the newly added return, replacing it with const out =, then going to the closing brace and adding return out.

I have a suggestion to optimize these steps. In fact, you could extract the variable in a single shortcut. Like so:

![](https://user-images.githubusercontent.com/1094774/115635479-cc0dee00-a2d9-11eb-834b-364e185b75ac.gif)

It's not a single shot, but I find extracting variables becoming as handy as F2 when you get used to it. 

Personally, I'd prefer keeping the 2 refactoring steps distinct. I find it more flexible. I don't feel like I'm constantly extracting the returned value when I add braces (e.g. sometimes it's to add some statements earlier, a guard clause, etc.).

Now, I'm open to the discussion. I'd like to find a solution that allows everyone to customize the experience to fit their use-cases best. Maybe some sort of configuration? 🤔

**Comment by wmertens** [comment]
Ooh, I totally missed that feature! Yes, two steps are just fine then. I'll close this.
