### ISSUE TITLE
"Convert let to const" appears in refactor menu in JS files with no "let" declarations

### ISSUE THREAD

**Issue by jonboiser** [nicoespeon/abracadabra#289]
## Describe the bug

In a JS/TS file like this:

```
const aString = 'hello';
const aNumber = 1;
const aArray = [];
const aObject = {};
```

The "convert let to const" refactor will be available whenever the cursor is past the "const" keyword. 

## How to reproduce

In a JS buffer write some code like the snippet above and open the refactor menu.

## Expected behavior

The "convert let to const" refactor is not shown in the middle of a "const" declaration.

## Screenshots

![image](https://user-images.githubusercontent.com/10248067/118854531-aef11e80-b889-11eb-95a3-8c3cbb8e620f.png)

## Additional information

5.3.0

_🧙‍ Add any other context about the problem here._

**Comment by nicoespeon** [comment]
Thank you @jonboiser, I never noticed and it was a bug indeed. I fixed it, I'll get it shipped in the following days 🙏

**Comment by nicoespeon** [comment]
@all-contributors please add jonboiser for bugs
