### ISSUE TITLE
Menu item references a command `abracadabra.splitMultipleDeclarations` which is not defined in the 'commands' section

### ISSUE THREAD

**Issue by tjx666** [nicoespeon/abracadabra#320]
![image](https://user-images.githubusercontent.com/41773861/123797740-14b8d780-d919-11eb-95e9-39d88705ac73.png)

**Comment by nicoespeon** [comment]
Oooooh, thanks for spotting! Interestingly the refactoring was still working, but the declaration was missing.
This will be fixed in the next release :+1
