### ISSUE TITLE
Renaming interface does not update project files

### ISSUE THREAD

**Issue by khusseini** [nicoespeon/abracadabra#321]
Hello there,
I just installed this extension with the hopes that I can refactor my library with ease. 
Unfortunately I found that when I use `Abracardabra Rename Symbol` in one `.ts` file, it would only rename the symbol in that file and not update the occurences in any other `.ts` or `.vue` files.

Can anyone nudge me in the right direction?

**Comment by nicoespeon** [comment]
Hey @khusseini 👋 

Abracadabra's rename refactoring is the native one from VS Code, except within a `.vue` file. 

Executing it from a `.ts` file should work fine with other `.ts` files. For `.vue` files I'm not so sure. Do you have the same behavior if you use the native rename (`F2`) instead?

When executing rename from a `.vue` file, the rename is limited inside the `<script>` tag indeed. VS Code doesn't support Vue files very well, and we're waiting for Vetur to implement this: https://github.com/vuejs/vetur/issues/610
Abracadabra can provide some help but doesn't work beyond the scope of a single `.vue` file.

**Comment by nicoespeon** [comment]
Closing the issue since it has been a few weeks. Feel free to [open a discussion](https://github.com/nicoespeon/abracadabra/discussions/new) if you need specific help with this 👍
