### ISSUE TITLE
TypeScript: inlining a variable declared with a cast produces an invalid expression if it is dereferenced

### ISSUE THREAD

**Issue by nicolasff** [nicoespeon/abracadabra#334]
## Describe what's missing

When a variable is declared with a cast using `as SomeType`, inlining it can produce invalid code.
The r-value is taken literally and the variable name is replaced with that value, but this isn't always possible without parentheses.

## Reproduction steps

With the following code:
```typescript
const saveButton = document.getElementById('btnSave') as HTMLButtonElement;
saveButton.disabled = true;
this.doSomethingElse(saveButton);
```

Placing the cursor on `saveButton` on the left side of the `=` sign and using the "inline variable" shortcut produces the following:

```typescript
document.getElementById('btnSave') as HTMLButtonElement.disabled = true;
this.doSomethingElse(document.getElementById('btnSave') as HTMLButtonElement);
```

The first line is invalid since TypeScript interprets `HTMLButtonElement.disabled` as the type to cast the expression to. The second line is correct.

Compiling this code produces the following error message:
> TS2713: Cannot access 'HTMLButtonElement.disabled' because 'HTMLButtonElement' is a type, but not a namespace. Did you mean to retrieve the type of the property 'disabled' in 'HTMLButtonElement' with 'HTMLButtonElement["disabled"]'?

(the error message from the TypeScript compiler correctly identifies the issue but provides a suggestion that isn't particularly relevant here).

## Expected behavior

In this particular case – an expression ending with a type cast – I believe the right behavior would be to wrap the expression in parentheses if it used directly. As for the second line, there is no need for parentheses when it used as a parameter.

The full output should be:

```typescript
(document.getElementById('btnSave') as HTMLButtonElement).disabled = true;
this.doSomethingElse(document.getElementById('btnSave') as HTMLButtonElement);
```

## Screenshots

In case it helps in addition to the repro code above, 2 screenshots.

*Before inlining:*
![image](https://user-images.githubusercontent.com/7276/124402264-076a6700-dce4-11eb-9689-1c25a86e5165.png)

*After inlining:*
![image](https://user-images.githubusercontent.com/7276/124402351-92e3f800-dce4-11eb-8389-e9d39a1adcef.png)

## Additional information

Note that this example dereferences the inlined variable by setting a property, but the same issue is present if a method is called on it. Adding a line like `saveButton.blur();` leads to `as HTMLButtonElement.blur()`, which is also invalid for the same reason.

- Version of the extension used: _v5.4.1_

Thanks for making this great extension!

**Comment by nicoespeon** [comment]
Hey @nicolasff 👋 

Thank you for such a detailed report! That was very helpful.

Indeed, this was a missed scenario. It would never have happened if we were only transforming the AST for this refactoring, but I found that would be detrimental to the original code style (it would be reformatted where it's inlined). So that's the trade-off…

Anyway, I was able to add a unit test to cover this, repro, and fix it for good 🌈 
I will ship a release containing this fix.

**Comment by nicoespeon** [comment]
@all-contributors please add nicolasff for bugs

**Comment by nicolasff** [comment]
Hi @nicoespeon,

Thanks for the quick fix! I've just upgraded and verified that it now works as expected :-)
I'm glad to see that it could be handled with a small change, and to see tests for it.

And thanks as well for the bug contributor mention, I can see this being a really good way to encourage reports.

Keep up the great work! From features to docs to handling reports, this project is exceptional.
