### ISSUE TITLE
`Inline`ing function deletes it without filling its callers

### ISSUE THREAD

**Issue by qpwo** [nicoespeon/abracadabra#340]
## Describe the bug

Inlining a function in a new file just deletes it without replacing its references.

## How to reproduce

In vscode make a new js file with the below contents, put your cursor on `foo`, hit cmd-shift-p and  abracadabra inline.

```js
function foo(x) { return (x * 2) + x + 3 }
function bar(x) { return foo(x) + 10 }
```

## Expected behavior

Thought I'd get this:

```js
function bar(x) { return ( (x * 2) + x + 3) + 10 }
```

## Screenshots

https://user-images.githubusercontent.com/10591373/125330095-4ddb4980-e314-11eb-8aae-f937809c4802.mov

## Additional information

Inlining variables is working. Pretty sure I'm on the latest vscode and the latest abracadabra

**Comment by nicoespeon** [comment]
Thank you for such a detailed report @qpwo 🙏  (love the screen recording)

That's a terrible bug—it's not even a complicated edge case! Fixing it is my next priority 😆

**Comment by nicoespeon** [comment]
@all-contributors please add qpwo for bugs

**Comment by qpwo** [comment]
Cool bot
