### ISSUE TITLE
Convert `for` loop to `for...of`

### ISSUE THREAD

**Issue by stagefright5** [nicoespeon/abracadabra#348]
## Is this request related to a problem? Please describe.

`forEach` does not allow you to break out of the loop. This could be helpful in those situations.

## Describe the solution you'd like

Converting `for` loop to `for...of` will help in those cases

## Additional context

Another way to solve it is to convert the `for` loops with `break` or `return` statements in its body to `.some` or `.every`

**Comment by nicoespeon** [comment]
@stagefright5 hey 👋 

Thanks for suggesting. Could you provide some before/after code snippets for this refactoring? Like typical examples of patterns you'd like to convert.

I think this refactoring could be a good one for first-time contributors, and code snippets would give them guidance for writing the tests.
