### ISSUE TITLE
[VUE] I can't build the AST from the source code in a Single File component

### ISSUE THREAD

**Issue by githubuser234** [nicoespeon/abracadabra#349]
If I want to rename a symbol in a .vue file (Single file component), I get the following error message

`😅 I'm sorry, something went wrong: I can't build the AST from the source code. This may be due to a syntax error that you can fix. Here's what went wrong: Adjacent JSX elements must be wrapped in an enclosing tag. Did you want a JSX fragment <>...</>? (3:0)`

The code producing this error looks like this

```
<template>
  <div>{{ test }}</div>
</template>

<script lang="ts">
import { Vue } from 'nuxt-property-decorator';
import Component from 'vue-class-component';

@Component({})
export default class Test extends Vue {
  test = 'test';
}
</script>
```

**Comment by nicoespeon** [comment]
Thanks for the code snippet @githubuser234, I realize there's a parsing issue in Abracadabra for such Vue files. It won't handle `<script>` tags that have attributes like `lang="ts"` 😅 

I'll get it fixed.

However, Abracadabra's capabilities for Vue are limited. It would work _within_ the `script` tag, but it won't rename the variable in the `<template>` tag.

Support for `.vue` file is limited. I'm not programming with Vue myself, so it's not my main focus. I hope it can still help you in some scenarios.
Hopefully, Vetur will start supporting such refactoring.

**Comment by nicoespeon** [comment]
That issue has been fixed. Abracadabra now knows how to parse Vue scripts that have attributes (e.g. `lang="ts"`).
