### ISSUE TITLE
"Flip if/else" returns in loops

### ISSUE THREAD

**Issue by j4k0xb** [nicoespeon/abracadabra#396]
## Describe the bug

When running the "Flip if/else" action on an if statement (without else) in a for/while loop, it converts it to a guard clause.

## How to reproduce

before:
```js
for (let index = 0; index < 5; index++) {
  if (index > 2) console.log(index); // 3, 4
}
console.log(123);
```
after:
```js
for (let index = 0; index < 5; index++) {
  if (index <= 2) return;
  console.log(index); // doesn't run anymore
}
console.log(123); // doesn't run anymore
```

## Expected behavior

It should *continue* instead

## Screenshots

_If applicable, add screenshots to help explain your problem._

## Additional information

- Version of the extension impacted: _v6.4.0_

- Related PR? #23

**Comment by nicoespeon** [comment]
Thanks for the catch and the detailed report @j4k0xb 👍 

You're right: it should rather `continue` when inside a loop. Will get this fixed!

**Comment by nicoespeon** [comment]
@all-contributors please add j4k0xb for bugs
