### ISSUE TITLE
Extract Interface refactoring does not find class with export flag

### ISSUE THREAD

**Issue by automatensalat** [nicoespeon/abracadabra#424]
## Describe the bug

When executing the "extract interface" refactoring on a `class` declared with the `export` flag, the refactoring shows an error message: *I didn't find a class to extract the interface from current selection 🤔*. When the flag is removed and the refactoring is performed, the refactoring completes successfully.

## How to reproduce

```ts
export class Foo {
  constructor(readonly numbers: number[]) {}

  bar(): number {
    return this.numbers.length;
  }
}
```
Put the cursor on the opening brace next to `Foo`, select "Abracadabra: Extract Interface" from the command palette. This generates the error message. 

Now remove the `export` flag, do it again and you'll end up with the extracted interface.

## Expected behavior

It should work just the same whether or not there is an `export` flag preceding the `class` definition.

## Additional information

- Version of the extension impacted: _v6.6.0_

**Comment by nicoespeon** [comment]
Thank you Tobias, you rock ❤️
