### ISSUE TITLE
Remove dead code should remove unused import

### ISSUE THREAD

**Issue by fabien0102** [nicoespeon/abracadabra#43]
## Describe what's missing

When I run `Remove dead code` on my imports, the unused one are not cleaned.

## Expected behavior

If it's dead / unused, remove the code.

## Screenshots

![image](https://user-images.githubusercontent.com/1761469/67287508-8ea98400-f4db-11e9-88ac-b70b0d75772e.png)

![image](https://user-images.githubusercontent.com/1761469/67287487-86514900-f4db-11e9-963a-ceb478f52a94.png)

## Additional information

- Version of the extension used: _v0.9.0_

**Comment by fabien0102** [comment]
![image](https://user-images.githubusercontent.com/1761469/67287602-b4368d80-f4db-11e9-917a-de53964db65b.png)

Vscode already have a helper for this. But not assignable to shortcut 😕 Let's see if we want to support this or not.

**Comment by nicoespeon** [comment]
As you mentioned, VS Code already has that Quick Fix. Actually, "Remove Dead Code" is also a Quick Fix, so it's not supposed to be assignable to a shortcut.

My recommandation to make Quick Fixes easy to use is to assign *them* a shortcut: I choosed `⌥ Enter`, so it's easy to trigger. The command ID is `editor.action.quickFix`.

I don't see clear improvement Abracadabra would bring over VS Code in that scenario. Thus, I think we won't do that 😉 

Nice proposition by the way. I like when you suggest ideas 👍
