### ISSUE TITLE
Support "Extract" on "return" keyword

### ISSUE THREAD

**Issue by automatensalat** [nicoespeon/abracadabra#441]
## Describe what's missing

I have many functions that `return` an expression, like a calculation or a chain of array transformation calls. Often I want to change the function body to "do something else" with the result of that expression, like log it for debugging purposes or apply some validation to it. 

I want to apply the `Extract Variable` refactoring, but in order to do so I have to select the entire expression first (and make sure I don't include the trailing semicolon), which is some minor annoyance. Instead, I just want to put the cursor on the `return` keyword and apply `Extract` which then applies to the entire returned expression.

## How would it work

For example, consider this function:
```ts
function addNumbers(arr: number[]): number {
	return arr.reduce((sum, current) => sum + current, 0);
}
```
I want to change it to this:

```ts
function addNumbers(arr: number[]): number {
        const extracted = arr.reduce((sum, current) => sum + current, 0);
	return extracted;
}
```

Currently I have to select `arr.reduce((sum, current) => sum + current, 0)` to do so.

I suggest expanding the `Extract` refactoring to also take into consideration the returned expression if the cursor is on the `return` keyword.

## Expected behavior

If the cursor is on the `return` keyword and there is an associated expression on it (`return;` need not apply) then the `Extract` refactoring works exactly as if the user selected the entire associated returned expression.

## Additional information

- Version of the extension used: _v6.7.1_

Edit: Maybe consider adding an `await` to the extracted variable if the value is a Promise (TS)

**Comment by nicoespeon** [comment]
Excellent suggestion. We could indeed extend the trigger to the `return` statement. That shouldn't be too hard to do. I'll give it a try tomorrow (and review your PR, thank you so much 🙏 )

**Comment by nicoespeon** [comment]
Actually, I think `return;` should be treated as `return undefined;` (which is what it actually does).

So I wonder whether we should do nothing… or transform the code into:

```js
const extracted = undefined;
return extracted;
```

So then you decide what you will return 🤔

**Comment by automatensalat** [comment]
Sure why not; it's the more general solution and might be useful for some workflows.

**Comment by nicoespeon** [comment]
Actually, it's easier to do nothing in this case, as you originally suggested. We could do what I described, but that would really be an edge case since the node is actually `null`, which is different from an `undefined` literal.

So it will do what you suggested for now 👍
