### ISSUE TITLE
Inline exported variables

### ISSUE THREAD

**Issue by nicoespeon** [nicoespeon/abracadabra#46]
## Describe what's missing

Today, Abracadabra limits its scope to the open file. Thus, we don't inline variables that are exported.

Also, unlocking inter-files refactorings will allow for a whole new set of refactorings, including [class-related refactorings](https://github.com/nicoespeon/abracadabra/issues/45) since classes are often separated in distinct files from my experience.

## How would it work

We should be able to index symbols across the editor workspace. Based on that, we should be able to extend refactoring outside of a single file.

That might change the way we handle refactorings too. Today, we parse the AST every time we trigger the refactoring. Tomorrow, we might want to have a language server or something that keeps track of the code structure, so it's faster to update.

## Expected behavior

When I inline an exported variable, it is inlined in other files that imports it.

## Additional thoughts

It would be awesome if we could rely on existing work. I guess TypeScript or VS Code already does that at some point. It might be the point where it'd be more valuable to contribute to native refactorings that trying to re-do the work in this extension though 🤷‍♂

**Comment by avik-so** [comment]
Don't know if this is helpful or not.
https://github.com/pmneo/ts-importer

**Comment by nicoespeon** [comment]
This is not something I can see being implemented in the near future. We need to dig into VS Code LSP to see what options are available. We'll do that in Hocus Pocus: https://github.com/nicoespeon/hocus-pocus/issues/3

Also, inlining variables in a big JS codebase might be risky and not reliable in general. I'm not sure. What I know is that we don't have enough knowledge for the moment to make it happen. 

Let's wait until we learn more about it. We'll revisit that later.
