### ISSUE TITLE
"Convert to forEach" mishandles re-assignment of array elements

### ISSUE THREAD

**Issue by alanhussey** [nicoespeon/abracadabra#477]
## Describe the bug

"Convert to forEach" seems to be changing _all_ indexed lookups to the new variable it defines, which means re-assignments are silently dropped.

## How to reproduce

Apply the refactoring "Convert to forEach" to the for loop in this sample:

```js
const myArray = [1,2,3];

for (let i = 0; i < myArray.length; i++) {
    myArray[i] = myArray[i].toString();    
}
```

For me, it produces this:

```js
myArray.forEach(myArray => {
    myArray = myArray.toString();    
});
```

## Expected behavior

After running, the transformed code continues to produce `['1', '2', '3']` for `myArray`. 

Additionally, the variable name for each element inside the forEach callback should be something other than the name of the array.

## Additional information

- Version of the extension impacted: _v6.8.0_

**Comment by nicoespeon** [comment]
Oh oh, thanks for reporting @alanhussey 👍 

Will have a look at this one soon.

**Comment by nicoespeon** [comment]
@all-contributors please add alanhussey for bug

**Comment by nicoespeon** [comment]
Thanks for reporting @alanhussey 👍 

These 2 issues were fixed and will be shipped in the next release.

**Comment by alanhussey** [comment]
That's great, thanks for the quick fix!
