### ISSUE TITLE
`Move Statement Down`/`Up` Always Add Semicolons

### ISSUE THREAD

**Issue by zardoy** [nicoespeon/abracadabra#481]
I think these commands are worth to mention in readme. However its annoying that in code that is not using semicolons they're always inserting them. I noticed that other refactorings and even builtin TS extension has tend to do that.

## How to reproduce

```ts
const a = 5
const b = 5
```
- use one of these commands on any line

## Expected Behaviour

No semicolons inserted.

**Comment by nicoespeon** [comment]
Thanks for reporting @zardoy 👍 
I'm not so surprised about it. Move Up/Down should be improved IMO, it's not fluid enough.

The reason why most refactorings tend to insert things like semicolons is that they usually modify the structure of the code (AST) and then print the new code based on this AST. The newly printed code will usually default to inserting semi-colons.

To prevent that, Abracadabra uses something called "recast" which aims to detect and preserve the style of the existing code when printing the modifications. But it's not perfect. In particular when we create whole new nodes.

That being said, I'm sure we can improve the detection of semi-colons and remove the inserted ones if they are not used. We did some improvements like this to better respect tab indentations (by default, it uses spaces).

**Comment by nicoespeon** [comment]
I just saw you mentioned

> I think these commands are worth to mention in readme

Actually, they are part of the "core refactorings" list: https://github.com/nicoespeon/abracadabra/blob/main/REFACTORINGS.md#move-statement-up

Do you have an idea to make them more visible?

Also, I started working on that. It shouldn't be too hard to achieve IMO 👍

**Comment by zardoy** [comment]
> Do you have an idea to make them more visible?

No, I didn't see them for some reason. 

> Also, I started working on that.

Would be great to have! Though this is not really a big issue since formatter can handle all this without creating any issues in the code. But it would be useful for folks who don't use it for some reason.

**Comment by nicoespeon** [comment]
> Though this is not really a big issue since formatter can handle all this without creating any issues in the code

I gave more thought to this and you are right. This is already handled by the formatter and you can typically have it run on save (I would recommend to).

It would be doable in Abracadabra, but would add some complexity (need to detect for each statement if it ends with a semicolon and adapts the resulting code after manipulating the AST). Finally, not using semi-colons isn't much frequent in JS codebases in my experience. I don't think a lot of people would run into this.

Thus, I'm closing this as won't fix it for now. If more people need this I would reconsider, but I would likely spend time on something more helpful.

**Comment by zardoy** [comment]
Lets just call range formatting provider at least so the moved statement will always be formatted. This is just one-line command, so it should be straightforward and would give better DX. Let me handle it.

>  Finally, not using semi-colons isn't much frequent in JS codebases in my experience.

Interesting, from my experience a lot of people starting to understand that they can omit them and save some time on not typing it.

**Comment by nicoespeon** [comment]
> Interesting, from my experience a lot of people starting to understand that they can omit them and save some time on not typing it.

Indeed, we are not using semi-colons at work for instance. But most codebases I've had to work with do use them (even Abracadabra actually).

But again, Prettier is automatically handling that for us so we don't really think about it!

> Lets just call range formatting provider at least so the moved statement will always be formatted. This is just one-line command, so it should be straightforward and would give better DX. Let me handle it.

Go for it. I will happily review/merge a PR if you get that done 😉
