### ISSUE TITLE
`Move Statement Down`/`Up` should move items within arrays

### ISSUE THREAD

**Issue by zardoy** [nicoespeon/abracadabra#491]
## Describe what's missing

`Move Statement Down`/`Up` should move items within arrays

## How would it work

```ts
const d = [
    {
        a: 5
    },
    {
        b: 5
    }
]
```
Extension says it can't move it.

## Expected behavior

There is should be a way to reposition array items. E.g. if cursor on the bracket it should move object up/down.

## Additional information

- Version of the extension used: 6.9.1

I'm really looking forward for this to be implemented!

**Comment by nicoespeon** [comment]
Oh, great example! I didn't notice that these object expressions were not supported. 

Alright, that will be part of the next release (I'll probably craft one today). Thanks for the suggestion 👍

**Comment by nicoespeon** [comment]
@all-contributors please add zardoy for ideas

**Comment by zardoy** [comment]
Thats what I use most in Webstorm. Thank you for looking into that. Now I just need to find a similar command for JSON files
