### ISSUE TITLE
Add/remove line breaks to/from argument list

### ISSUE THREAD

**Issue by brunnerh** [nicoespeon/abracadabra#494]
## Is this request related to a problem? Please describe.

One of the most common automatable code changes I perform is moving arguments onto their own lines. This is especially true for TS, whose type annotations can make the signature much longer.

## Describe the solution you'd like

A code action that puts arguments onto their own lines and a reverse operation that puts all arguments onto one line (useful if arguments got removed and a single line makes more sense).

e.g. from:

```ts
function test(name: string, age: number, street: string, houseNumber: number, city: string, zipCode: string, country: string) {
	// ...
}
```

to:

```ts
function test(
	name: string,
	age: number,
	street: string,
	houseNumber: number,
	city: string,
	zipCode: string,
	country: string) {
	// ...
}
```

An option to choose how the end parenthesis is handled would be great, personally I would format this using an additional trailing comma and the parenthesis on a new line, i.e.:

```ts
function test(
	name: string,
	age: number,
	street: string,
	houseNumber: number,
	city: string,
	zipCode: string,
	country: string,
) {
	// ...
}
```

Note: This is invalid for rest parameters, e.g.

```ts
function test2(
	name: string,
	...items: string[], // A rest parameter or binding pattern may not have a trailing comma. ts(1013)
) {
	// ...
}
```

## Additional context

Such features are available for C# in VS and in the respective VS Code extension:

![image](https://user-images.githubusercontent.com/834235/151017103-8b363857-2f26-408c-b845-ea0a28c0ae09.png)

This offers multiple additional methods, but they tend to be inconsistent or prone to inconsistency.

`Wrap every parameter -> Indent all parameters`  
What I described above.

`Wrap every parameter -> Align wrapped parameters`
```csharp
public static void Method(string name,
                          int age,
                          string street,
                          int houseNumber,
                          string city,
                          string zipCode,
                          string country)
{

}
```
The alignment breaks easily if return type, visibility or method name changes. 

`Wrap every parameter -> Indent wrapped parameters`
```csharp
public static void Method(string name,
    int age,
    string street,
    int houseNumber,
    string city,
    string zipCode,
    string country)
{

}
```
Why, though?

**Comment by nicoespeon** [comment]
Closing the issue because it's not something I see implementing in Abracadabra. 

Hope my indications about Prettier help. Let me know otherwise 😉

**Comment by brunnerh** [comment]
I am aware that this is more formatting than refactoring, I am also aware of Prettier.
As you noted, Prettier is unfortunately very opinionated and its opinions do not mesh with mine.

Also, I would rather not hand off line breaks like these to fully automated tooling, there sometimes are corner cases where you might want to do things differently. E.g. using "logical" arrangements like this:

```ts
function test(
  firstName: string, lastName: string,
  street: string, houseNumber: number,
  zipCode: string, city: string, country: string,
) {
  // ...
}
```
