### ISSUE TITLE
Inline into template string loses the ${} brackets

### ISSUE THREAD

**Issue by rsxdalv** [nicoespeon/abracadabra#512]
## Describe the bug

Inlining a variable used in a template string results in a malformed code, due to missing ${} brackets.

## How to reproduce

In the following code, attempting to inline authToken results in:

```ts
  const authToken = AuthStore.get("authToken");
  return fetch(url, {
    method: "post",
    headers: {
      Accept: "application/json",
      "Content-Type": "application/json",
      Authorization: `Bearer ${authToken}`,
    },
    body: JSON.stringify(payload),
  })
```

```ts
  return fetch(url, {
    method: "post",
    headers: {
      Accept: "application/json",
      "Content-Type": "application/json",
      Authorization: `Bearer AuthStore.get("authToken")`,
    },
    body: JSON.stringify(payload),
  })
```

## Expected behavior

```ts
return fetch(url, {
    method: "post",
    headers: {
      Accept: "application/json",
      "Content-Type": "application/json",
      Authorization: `Bearer ${AuthStore.get("authToken")}`,
    },
    body: JSON.stringify(payload),
  })
```

## Additional information

- Version of the extension impacted: v6.10.0

Also this extension is like sliced bread for TypeScript, <3 u guys.

**Comment by nicoespeon** [comment]
Ooooh, great catch @rsxdalv 👍 

That was a feature I added in v6.9 for literals… but I forgot to limit it to _only_ literals 🤦 
Just fixed it. Thank you again for reporting with all the details. It was really helpful to create a test case!

**Comment by nicoespeon** [comment]
@all-contributors please add rsxdalv for bugs

**Comment by rsxdalv** [comment]
Awesome!
