### ISSUE TITLE
Improve the scope of the refactor 'move to existing file'

### ISSUE THREAD

**Issue by joshjm** [nicoespeon/abracadabra#514]
## Describe what's missing

This refactor only seem to work for function definitions. But doesnt work for arrow functions, moving consts, interfaces, and the like. 
These are also things that would be commonly moved to an existing file.

## How would it work

The move to new file should also move these arrow functions/consts/interfaces/types etc as well as just function definitions.

## Expected behavior

Evoking the refactor while selecting this expanded range of objects will result in them getting moved to a new file, with imports updates, rather than the plugin reporting back that 'i didnt find the code to move from the current selection'

## Screenshots

n/a

## Additional information

- Version of the extension used: v6.11.0

**Comment by joshjm** [comment]
hmm looking at the source, it looks like this refactor should already be able to move things like types, though it doesnt seem to work my project. I'll investigate a little more, then might convert issue to a bug rather than improvement

**Comment by joshjm** [comment]
hmm, pulling the code, and running the tests for the move to existing file and i get all passes. Might be something specific to my own setup thats preventing it

**Comment by joshjm** [comment]
Ok, looks like the issue really is that the refactoring doesn't work with exported items. eg:
```
export type SomeType = string;
```
Is this just that the extension isn't smart enough to look for the imports in other files? ie, this is by design?

**Comment by nicoespeon** [comment]
Hey @joshjm, thanks for reporting!

I'm gonna have a look at this. It's possible that I decided to _not_ handle the exported symbols when I implemented this. I think we can handle these: we could make sure the original code still exports the symbol, so it doesn't break the API.

I'll give it a look and let you know 👍

**Comment by nicoespeon** [comment]
@joshjm I gave it a try and got it working for exported nodes (named and default). I'll ship that in the next release 😉 

Thank you for the suggestion ❤️

**Comment by nicoespeon** [comment]
@all-contributors please add joshjm for ideas

**Comment by joshjm** [comment]
You legend! thankyou! That for sure beats needing to swap editor to webstorm for something so simple 😅
I have a bunch more refactoring i need to do on a project, so i'll give it a spin (probably on monday) and let you know how it goes 🙏
