### ISSUE TITLE
Add a Table Of Contents to README and CONTRIBUTING files

### ISSUE THREAD

**Issue by HEYGUL** [nicoespeon/abracadabra#53]
## Describe what's missing

The documentation is really great and give plenty of information.
As I started to contribute, I unfortunately missed some useful links about AST.
The links are actually provided in the `CONTRIBUTING` file.
A table of contents, with clickable titles, might help to get a quick look on the file structure and go to the desired section.

## How would it work

I suggest to add a basic table of contents.
e.g.: https://github.com/jamiebuilds/babel-handbook/blob/master/translations/en/plugin-handbook.md#table-of-contents

## Expected behavior

Provided guidelines have a dynamic table of contents.

## Screenshots

Not applicable.

## Additional information

 Not applicable.

**Comment by nicoespeon** [comment]
@all-contributors please add HEYGUL for ideas and code
