### ISSUE TITLE
Make "Move to existing file" work with variable declarations

### ISSUE THREAD

**Issue by qpwo** [nicoespeon/abracadabra#543]
## Describe the bug

Whenever I try to move code in my project i get "I didn't find the code to move from current selection"

## How to reproduce

Clone & open https://github.com/qpwo/test-abracadabra and open it in vscode. Try to move `two` from fileA to fileB.

## Expected behavior

Should move it to fileB.

## Screenshots

![image](https://user-images.githubusercontent.com/10591373/157339699-f3b453bd-4d44-4f22-86d0-4c4b155e8164.png)

## Additional information

v6.11.0

**Comment by nicoespeon** [comment]
@qpwo ah ah, great catch!

In fact, it's not a bug but… not implemented 😅 
"Move to Existing File" only works for Function declarations, Type Alias declarations, and Interface declarations (yet). 

I agree that we should be able to move Variable declarations too! I'll edit the issue to reflect that request. I think I can get it done this week—I worked on this one recently, so the timing is perfect.

**Comment by nicoespeon** [comment]
BTW, 👏 for the repository to repro. That is a perfect only playground (https://github.dev/qpwo/test-abracadabra) 👍

**Comment by nicoespeon** [comment]
@allcontributors please add qpwo for ideas

**Comment by qpwo** [comment]
Oh dope wow pretty fast

**Comment by qpwo** [comment]
![works-like-a-charm](https://user-images.githubusercontent.com/10591373/158281348-970b9def-5af1-4ef8-a3ba-a69c45adb74a.gif)

Works like a charm!
