### ISSUE TITLE
Inline async function generates duplicate "await" keyword

### ISSUE THREAD

**Issue by automatensalat** [nicoespeon/abracadabra#548]
## Describe the bug

When applying the "inline" refactoring to an async function that only has a single `await` statement in it, the resulting code will have two `await`s instead of a single one:

```ts
export async function callerAsync() {
	await smallFunctionAsync();
}

async function smallFunctionAsync() {
	await someOtherDelegate();
}
```

after inline `smallFunctionAsync`:

```ts
export async function callerAsync() {
	await await someOtherDelegate();
}

```

## How to reproduce

See above code

## Expected behavior

I expect there to be only a single `await` in the generated code

## Additional information

- Version of the extension impacted: _v6.12.0_

**Comment by nicoespeon** [comment]
Great catch, thanks @automatensalat 👍
