### ISSUE TITLE
Convert if/else to ternary could be more intelligent with refactoring return statements

### ISSUE THREAD

**Issue by David-Else** [nicoespeon/abracadabra#56]
I am not sure if this is a bug or a feature request. As soon as I started using this plugin I am finding immediately many cases like this:

```
function calculateYear(selectedDates) {
  if (
    selectedDates[0].getMonth() === 0 ||
    (selectedDates[0].getMonth() === 1 && selectedDates[0].getDate() < 4)
  ) {
    return selectedDates[0].getFullYear() - 1;
  }
  return selectedDates[0].getFullYear();
}
```
abracadabra does not seem to recognise this as an ideal chance to convert to a ternary, and there is no lighbulb or option to convert. It would be great if it did see this opportunity and output:
```
function calculateYear(selectedDates) {
  return selectedDates[0].getMonth() === 0 ||
    (selectedDates[0].getMonth() === 1 && selectedDates[0].getDate() < 4)
    ? selectedDates[0].getFullYear() - 1
    : selectedDates[0].getFullYear();
}
```
I know this is not a great bit of logic in my code, but this is just an example, I am having a go at refactoring an old app :) Cheers!

**Comment by nicoespeon** [comment]
Hi @David-Else 👋 

Thank you for pushing this. This is what I call "Improvements". A typical scenario that Abracadabra could recognize to apply an existing refactoring.

This one can be frequent when we use guard clauses indeed. I'll definitely love to implement this one 👍 

I'll keep you posted.

**Comment by David-Else** [comment]
Cheers!

Sorry to go off topic, but I just saw this new feature in the new VSCode 1.41 release that is about to come out this week and thought it might help this extension?

https://code.visualstudio.com/docs/editor/refactoring#_keybindings-for-code-actions

**Comment by nicoespeon** [comment]
That's very interesting.

From what I understand, that will allow the user to configure personal shortcuts for actions that are only available through Code Actions (= Quick Fixes). So you will be able to set a shortcut to trigger "Convert If/Else to Ternary" for example.

From the extension standpoint though, I don't see how we could use that. Maybe Abracadabra could leverage it to make VS Code native "extract function" triggers with a shortcut. I'll have a look.

Again, thanks for sharing 👍
