### ISSUE TITLE
Generic Interfaces cannot `Move to existing file`

### ISSUE THREAD

**Issue by jtwigg** [nicoespeon/abracadabra#574]
## Describe the bug

`Move to existing file` will work for NON-generic interfaces, but not Generic interfaces.

### Works
```
export interface EmptyWorks {
    value: number
}
```

### Doesn't work
```
export interface EmptyInterface<T> {
    value: T
}

```

When moving `EmptyInterface` I receive
```
I'm sorry, I can't move this, it has references that can't be imported (circular reference) 😅
```

## Expected behavior

The generic `EmptyInterface` should likewise be relocatable.

## Screenshots
![image](https://user-images.githubusercontent.com/1237233/165557690-7287667e-6e5e-4084-8a69-38d8f7ea2256.png)

## Additional information

- Version of the extension impacted: _vX.X.X_

_🧙‍ Add any other context about the problem here._

**Comment by nicoespeon** [comment]
Thank you for this great report! Indeed, the generic was messing up with the operation. I fixed that 👍

**Comment by nicoespeon** [comment]
@all-contributors please add jtwigg for bugs
