### ISSUE TITLE
Error when using "Inline" on a function

### ISSUE THREAD

**Issue by automatensalat** [nicoespeon/abracadabra#575]
## Describe the bug

Hi there, I'm getting this error message in a special case when performing *Inline* on a function:

>😅 I'm sorry, something went wrong: Property key of ObjectProperty expected node to be of a type ["Identifier","StringLiteral","NumericLiteral"] but instead got "MemberExpression"

I have not yet figured out what exactly provokes the error, but here is a reproducable example:

## How to reproduce

```ts
export function callingFunction() {
  const args = { foo: "bar" };
  myFunction(args.foo);
}

// to be inlined
function myFunction(foo: string) {
  const logger = createLogger();
  logger.log("a", "b", {
    foo: foo,
  });
}

function createLogger() {
  return {
    log: (arg: any, arg2: any, arg3: any) => console.log(arg, arg2, arg3),
  };
}

```

Put cursor on the declaration of `myFunction`, execute the `Inline` command

## Expected behavior

It should, well, inline the body of the function without errors.

## Additional information

- Version of the extension impacted: _v6.13.0_

**Comment by nicoespeon** [comment]
Dang, that's because we were trying to replace the `foo` key too 🤦 

Thanks for reporting, this is fixed!
