### ISSUE TITLE
Move to existing file errors (Typescript)

### ISSUE THREAD

**Issue by sam-s4s** [nicoespeon/abracadabra#632]
## Describe the bug

When trying to "Move to existing file" on a typescript function, I got this error:
```
😅 I'm sorry, something went wrong: I can't build the AST from the source code. This may be due to a syntax error that you can fix. Here's what went wrong: Unexpected token (309:39)
```

The code is perfectly good Typescript, 1,100 lines of it though :P

That line it talked about was this...
```
        return currentValue < minValue ? current : min;
```
...how exciting...

I figure something in the abracadabra extension has a problem with Typescript, so I deleted everything except for the stuff I was trying to move, and the 2 small functions that they themselves use.

It then gave me this error:
```
I'm sorry, I can't move this, it has references that can't be imported (circular reference) 😅
```
## Expected behavior

Both of the above errors are not correct, as the syntax is fine, and there are no circular references.

Using the latest version, 6.14.4, freshly installed.

I'm wondering if it's just that it doesn't actually work with Typescript?

**Comment by nicoespeon** [comment]
Hey @sam-s4s 👋 

Thanks for the report and your patience. The extension should work fine with TS, but I suspect it's running into some edge-case that I'm not handling yet.

Would you have a code snippet to repro the issue? There is something the refactoring considers a circular reference and that may be a mistake.

A code snippet would help me debug and fix it!
Thanks!

**Comment by tsteckenborn** [comment]
Hi @nicoespeon,

happened to encounter a strange behavior with regards to "Move to an existing file" with TypeScript.

`I'm sorry, I can't move this, it has references that can't be imported (circular reference) 😅`

Moving to a new file worked without any issues. Unfortunately can't quickly reproduce that and can't share the sample... 😢

**Comment by nicoespeon** [comment]
FYI, the "Move to existing file" refactoring has been removed in favor of TypeScript 5.2 refactoring (that works better). It should be available in VS Code.

See https://github.com/nicoespeon/abracadabra/issues/915#issuecomment-1773611547
