### ISSUE TITLE
Convert to forEach fails if array is nested in object

### ISSUE THREAD

**Issue by automatensalat** [nicoespeon/abracadabra#659]
## Describe the bug

The "Convert for-loop to forEach" does not work if the accessed array is not a pure literal but a nested expression like `a.b` (not sure those are the correct terms tbh):

```ts
 const bar = [1, 2, 3];
  // refactoring works
  for (const item of bar) {
    console.log(item);
  }

  const foo = {
    bar: [1, 2, 3],
  };
  // refactoring fails
  for (const item of foo.bar) {
    console.log(item);
  }
```
I get an error message saying that it can't find a valid for loop to execute the refactoring on. 

## Expected behavior

It should just work the same way as if the accessed array is a simple variable expression, i.e. the above code should be transformed to `foo.bar.forEach(item => {
    console.log(item);
  });`

## Additional information

- Version of the extension used: _v6.14.4_

**Comment by nicoespeon** [comment]
Ah ah yes! It was an easy one. The reason this wasn't working is because... it wasn't supported. I made it accept Member Expressions (that's the name of `foo.bar` expressions), so that will work in the next release 😉 

Thanks for raising it up!
