### ISSUE TITLE
New Refactoring: Simplify ternary expression

### ISSUE THREAD

**Issue by visusnet** [nicoespeon/abracadabra#66]
## Is this request related to a problem?

I find myself refactoring boolean expressions quite often and sometimes I (i.e. the available refactorings) end up with one of the following expressions:
```javascript
const one = a ? b : true;
const two = a ? b : false;
const three = a ? true : c;
const four = a ? false : c;
const five = a ? true : false;
const six = a ? false : true;
```

All of these can be simplified:
```javascript
const one = !a || b; // = a ? b : true;
const two = Boolean(a) && b; // = a ? b : false;
const three = Boolean(a) || c; // = a ? true : c;
const four = !a && c; // = a ? false : c;
const five = Boolean(a); // = a ? true : false;
const six = !a; // = a ? false : true;
```

If ``a`` is boolean, the casts are redundant and can be omitted.

## Describe the solution you'd like

I‘d love a refactoring on any ternary that simplifies these expressions.

## Additional context

Additionally, an "Expand to ternary expression" refactoring which is the inverse of the described "Simplify ternary expression" would be awesome.

There are other expressions which can be simplified, e.g.:
```javascript
const seven = a || !a; // => a
const eight = true || b; // => true
const nine = false || b; // => b
const ten = true || true; // => true
const eleven = false || false; // => false
const twelve = true || false; // => true
const thirteen = false || true; // => true
const fourteen = a && a; // => a
const fifteen = a && !a; // => false
const sixteen = a && true; // => Boolean(a)
const seventeen = a && false; // => false
const eighteen = true && a; // => a
const nineteen = false && a; // => false
const twenty = a && b || a && c; // => a && (b || c)
const twentyOne = !(a && b); // => !a || !b
const twentyTwo = !(!a || !b); // => Boolean(a && b)
...
```
This feature request covers ternary expressions but my desired solution would be called "Simplify expression“ and it would recursively try to find the shortest /most simple version of a given expression.

**Comment by David-Else** [comment]
Fantastic idea! I don't think that all of these simplified versions are actually easier to read, but maybe there is some algorithm that could pick up on easy wins with ternary expressions?

Here is a resharper one: https://www.jetbrains.com/help/resharper/SimplifyConditionalTernaryExpression.html

>  If your ternary expression (an expression of the form a ? b : c) contains a boolean constant as either b or c, it can be converted to a much simpler expression. For example, this
> ```
> public bool CanVote
> {
>   get { return myAge >= 16 ? isCitizen : false; }
> }
> ```
> can be simplified to this:
> ```
> public bool CanVote
> {
>   get { return myAge >= 16 && isCitizen; }
> }
> ```
>
