### ISSUE TITLE
New Refactoring: Move to an existing file

### ISSUE THREAD

**Issue by visusnet** [nicoespeon/abracadabra#67]
## Is this request related to a problem?

There already is a built-in move to file refactoring but it only moves functions to a new file with the function name as file name.

## Describe the solution you'd like

A "Move to file" refactoring should be able to either move the function to a new file (already built-in) or an existing file. Imports and global constants should be moved (or copied if moving is not possible because they are used elsewhere) as well.

**Comment by nicoespeon** [comment]
I can totally relate to this request. Moving to an existing file will indeed be very helpful 👍 

Plus, that should not be really hard to implement. Most of the work is to find the imported identifiers and imported accordingly.

**Comment by OliverJAsh** [comment]
This suggestion has also been filed in the TS repo https://github.com/microsoft/TypeScript/issues/29988

**Comment by OliverJAsh** [comment]
The TS implementation of "move to file" is ~600 lines 🤯 https://github.com/microsoft/TypeScript/pull/23726/files#diff-04f31d59e046b19e11aff2b68559bad9R1

**Comment by nicoespeon** [comment]
FYI, I have something that works for function declarations. I still need to handle eventual references in these functions that should be imported/moved/copied in the other file so the code still works.

This is the kind of feature that will require a lot of back and forth to optimize the UX, there are plenty of use-cases.

I plan to release moving "function declarations" first. Then we'll iterate with other types (e.g. variable declarations, class declarations, etc.).

**Comment by nicoespeon** [comment]
As usual, there are still some edge cases to cover with moving "function declarations".

Here's the remaining work until this lands in Abracadabra:

- [x] What if function references imported identifiers?
- [ ] What if function references identifiers from the local file? _(we'll avoid a circular import and copy them for now)_
- [ ] Document the new refactoring

**Comment by nicoespeon** [comment]
Exciting news: this is working for function declarations now!

![moving-to-existing-file](https://user-images.githubusercontent.com/1094774/103906193-95ff8200-50cd-11eb-8ba4-3433460bdb1d.gif)

I'll be releasing it with a couple of fixes, probably by the end of the week.

Thanks for suggesting, it was a long ride.
There will certainly be iterations on this to solve edge cases and move other type of nodes (e.g. classes, variables).

**Comment by visusnet** [comment]
Wow, awesome! This will help a lot. Great work!

**Comment by clouedoc** [comment]
@nicoespeon hello ! Did you release this feature yet? I'm very interested in it.
