### ISSUE TITLE
Wrong nested loop detected

### ISSUE THREAD

**Issue by j4k0xb** [nicoespeon/abracadabra#703]
## Describe the bug

The `Toggle braces (loop)` and `Convert to forEach` refactorings always change the outer-most loop, regardless of the cursor position.

### Toggle braces
```js
for (let i = 0; i < 3; i++) {
  for (let j = 0; j < 4; j++) {[cursor]
    console.log(i * j);
  }
}
```
Result:
```js
for (let i = 0; i < 3; i++)
  for (let j = 0; j < 4; j++) {
    console.log(i * j);
  }
```

### Convert to forEach
```js
for (const x of items) {
  for (const y of items) {[cursor]
    console.log(x * y);
  }
}
```
Result:
```js
items.forEach(x => {
  for (const y of items) {
    console.log(x * y);
  }
});
```

## Expected behavior

Change the loop closest to the cursor:
```js
for (let i = 0; i < 3; i++) {
  for (let j = 0; j < 4; j++) console.log(i * j);
}
```

## Additional information

- Version of the extension impacted: _v6.15.3_

**Comment by nicoespeon** [comment]
@all-contributors please add j4k0xb for bugs

**Comment by nicoespeon** [comment]
@j4k0xb thanks for reporting. These have been captured in tests and fixed!
I'll release that change soon.

Your code snippets where really helpful 💯
