### ISSUE TITLE
Convert to template literal shoud not be propose on imports

### ISSUE THREAD

**Issue by fabien0102** [nicoespeon/abracadabra#73]
## Describe the bug

Abracadabra propose to transform my import into template literal, even if it's valid, I'm not sure we should propose this refactor here 😁 

## How to reproduce

Import something and clic on the bulb!

## Expected behavior

Nothing! Leave my import alone 😅 

## Screenshots

![image](https://user-images.githubusercontent.com/1761469/73262542-bab95d00-41ce-11ea-9c10-aac73e7bb140.png)

**Comment by timvancleef** [comment]
A quick and relatively easy fix would be to check if the parent node is of type `ImportStatement`.
Not sure if this is sufficient though 🤔

**Comment by nicoespeon** [comment]
Yep, it should do it. Hopefully that's easy to unit test and tackle 👍
