### ISSUE TITLE
New refactoring: Yoda flip

### ISSUE THREAD

**Issue by ramunsk** [nicoespeon/abracadabra#749]
## Is this request related to a problem? Please describe.
Some people love [Yoda conditions](https://en.wikipedia.org/wiki/Yoda_conditions), some people hate them. While Yoda conditions do have their [pros and cons](https://knowthecode.io/yoda-conditions-yoda-not-yoda) flipping a condition involves cut'n'paste, some cursor movements and sometimes logic reverse. It may be not an issue for a couple of places in code but when refactoring a big code base this raises the amount of "bleeps" quite significantly. 

## Describe the solution you'd like
`'🙂' === [cursor]emotion` -> `Ctrl+.` -> `Yoda flip` -> `emotion[cursor] === '🙂'`

Refactoring should also account for comparison operator:
- `==`, `===`, `!=`, `!==` should remain unchanged
- `>`, `>=`, `<`, `<=` should be flipped

**Comment by nicoespeon** [comment]
![image](https://user-images.githubusercontent.com/1094774/200939263-3626f383-6c72-4f81-95f5-360e0c7cad2b.png)

**Comment by nicoespeon** [comment]
@all-contributors please add ramunsk for ideas

**Comment by ramunsk** [comment]
@nicoespeon @j4k0xb 
Thanks for new feature. Time-to-market was incredibly short and new refactoring is already busy working 
👍
