### ISSUE TITLE
"Flip if/else" may change code semantics by removing parentheses 

### ISSUE THREAD

**Issue by yume-chan** [nicoespeon/abracadabra#753]
## Describe the bug

"Flip if/else" refactor will remove parentheses in condition expression, but that may change the semantics of the code.

## How to reproduce

```ts
if (false && (false || true)) {
  console.log('true');
} else {
  console.log('false');
}
```

1. Run this code, it will output "false"
2. Use "Flip if/else" refactor on the `if` statement, the output is

```ts
if (!(false && false || true)) {
  console.log('false');
} else {
  console.log('true');
}
```

4. Run the result code.
5. It outputs "true" now

## Expected behavior

It still output "false"

## Additional information

- Version of the extension impacted: v6.17.0

**Comment by nicoespeon** [comment]
Thanks for reporting @yume-chan ❤️ 

This is fixed and will be part of next release.

**Comment by nicoespeon** [comment]
@all-contributors please add yume-chan for bugs
