### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by visusnet** [nicoespeon/abracadabra#79]
This is a continuation of #77.

**Comment by nicoespeon** [comment]
Nice, thank you @visusnet 🙏 

I have a busy week (meetups & conference all week long 😅) so I'll review all of that next week-end.

![canada-drink](https://user-images.githubusercontent.com/1094774/75120520-69c84780-565a-11ea-9ad7-6acece08fb67.gif)

Have a nice week!

**Comment by nicoespeon** [comment]
Triggering Abracadabra on a 2.3k LOC file.

Before:

![image](https://user-images.githubusercontent.com/1094774/77814031-e26c5a80-7083-11ea-9d67-13e9cad89423.png)

After:

![image](https://user-images.githubusercontent.com/1094774/77814020-c8327c80-7083-11ea-90c3-26e707c4d55f.png)

That's a 10x improvement 👏 

Closing this. Thank you @visusnet
