### ISSUE TITLE
Wrap with JSX Fragment

### ISSUE THREAD

**Issue by leodr** [nicoespeon/abracadabra#791]
## Is this request related to a problem? Please describe.

Adding a React Fragment around a component because you want to add a sibling to it is quite tedious.

## Describe the solution you'd like

When selecting a JSX tag you could be offered a refactoring option to wrap this tag in a React Fragment (`<>...</>`). If possible also when selecting multiple tags.

## Additional context

/

---

Thanks for the project, very helpful :)

**Comment by nicoespeon** [comment]
Thanks for the suggestion! It would be cool indeed, and it sounds like a simple refactoring to implement actually.

BTW, if you don't wanna wait to have this, I can recommend installing the [P42 extension](https://marketplace.visualstudio.com/items?itemName=p42ai.refactor). It's a good one too. There are some overlaps with Abracadabra, but it has the "Surround with Fragment" refactoring already when you select some JSX:

![surround with fragment](https://user-images.githubusercontent.com/1094774/212089397-7f490699-c434-45e9-bba5-3f434c4aea11.png)
