### ISSUE TITLE
AST parse fail when object contains a comment and `satisfies` operator

### ISSUE THREAD

**Issue by byronwall** [nicoespeon/abracadabra#795]
## Describe the bug

Abracadabra fails to parse the AST when an object contains a comment and ends with the `satisfies` operator.

## How to reproduce

Code that fails to parse:

```ts
// code fails to parse an AST
const b = "565656";
const a = console.log(b);

type DummyType = {
  dummy: number;
};

const defaultStore = {
  // **** this comment inside the object breaks parsing -- remove this line or `satisfies DummyType` and it works
  dummy: 0,
} satisfies DummyType;

```

Code that parses OK (move the comment outside of the object and retain `satisfies`:

```ts
const b = "565656";
const a = console.log(b);

type DummyType = {
  dummy: number;
};

// **** this comment inside the object breaks parsing -- remove this line or `satisfies DummyType` and it works
const defaultStore = {
  dummy: 0,
} satisfies DummyType;

```

This also works (remove the satisfies but retain the comment):

```ts
const b = "565656";
const a = console.log(b);

type DummyType = {
  dummy: number;
};

const defaultStore = {
    // **** this comment inside the object breaks parsing -- remove this line or `satisfies DummyType` and it works
  dummy: 0,
} 

```

## Expected behavior

Expected the parsing to work, same as when `satisfies` or the comment is missing.

## Screenshots

Error given when attempting to inline variable `b`:

![image](https://user-images.githubusercontent.com/495404/212365536-de47ada0-f394-40ad-a863-4743cc6ae15f.png)

## Additional information

- Version of the extension impacted: _v6.18.2_

This was originally reported as issue #785.  The new complication is the presence of the comment which further breaks parsing.

**Comment by nicoespeon** [comment]
Awesome, thanks for the detailed report with code snippets and all. You rock :gri

**Comment by nicoespeon** [comment]
@byronwall well, turns out it was an issue with Recast that wasn't up-to-date yet. I upgraded the library and it's working fine now!

I'll release that in the following days. Thank you again for the detailed repro 🙏
