### ISSUE TITLE
Inlining JSX removes curly braces

### ISSUE THREAD

**Issue by automatensalat** [nicoespeon/abracadabra#801]
## Describe the bug

When performing the `Inline` refactoring on a JSX element targeting a JSX prop, the refactoring omits the curly braces `{}` around the prop value, resulting invalid syntax: 

```jsx
function MyComponent() {
  const header = <span>hello</span>; // <-- inline this
  return <Menu header={header} />
}

// resulting in:
function MyComponent() {
  return <Menu header=<span>hello</span> />
}
```

## How to reproduce

See above code

## Expected behavior

It should retain the `{}` curly braces: 
```jsx
function MyComponent() {
  return <Menu header={<span>hello</span>} />
}
```

## Additional information

- Version of the extension impacted: _v6.18.2_

_🧙‍ Add any other context about the problem here._

**Comment by nicoespeon** [comment]
Thanks for the report. That should be fixed now! I'll cut a new release tomorrow.
