### ISSUE TITLE
Extract refactoring runs on JSX attribute

### ISSUE THREAD

**Issue by automatensalat** [nicoespeon/abracadabra#802]
## Describe the bug

The Extract refactoring can be run on JSX attributes, resulting in invalid syntax:

```jsx
function MyComponent() {
	return <div id="test">Hello</div>;
}
```
Run "Extract" on attribute "id", results in

```jsx
function MyComponent() {
	const extracted = id;
	return <div {extracted}="test">Hello</div>;
}
```

## How to reproduce

See above

## Expected behavior

I don't know if there's ever a way this can be useful; I think the refactoring should just show an error message in this case.  

## Additional information

- Version of the extension impacted: _v6.18.2_

**Comment by nicoespeon** [comment]
Thanks for reporting! I handled this case and now it will resolve the closest extractable chunk.

In this case, it will extract the whole JSX Element:

```tsx
function MyComponent() {
  const extracted = <div id="test">Hello</div>;
  return extracted;
}
```

**Comment by automatensalat** [comment]
I suppose it could also extract the value of the attribute, i.e. 
```jsx
function MyComponent() {
  const extracted = "test";
  return <div id={extracted}>Hello</div>;
}
```

Not sure which behavior would be more helpful / expected.

**Comment by nicoespeon** [comment]
Maybe… I went for the consistent behavior of "extract the closest extractable node", I'm not sure how easy it would be to add this one special case at the moment. I think that's fine, you would put your cursor on the value to extract the value and that should work fine 👍
