### ISSUE TITLE
Inline async arrow function misses braces

### ISSUE THREAD

**Issue by automatensalat** [nicoespeon/abracadabra#816]
## Describe the bug

I have this code:

```ts
const foo = async (a: number) => {
  console.log(a);
};

const bar = async () => {
  await foo(3);
};
```

I try to inline `foo`. This then generates this code: 

```ts
const bar = async () => {
  await async (a: number) => {
  console.log(a);
}(3);
};
```

Resulting in a compile error "Cannot find name 'async'".

## How to reproduce

See above

## Expected behavior

It should generate compileable code. In this case it's missing braces around the inlined function:

```ts
const bar = async () => {
  await (async (a: number) => {
    console.log(a);
  })(3);
};
```

## Additional information

- Version of the extension impacted: v6.19.0

**Comment by nicoespeon** [comment]
Thanks for the detailed examples, it helped me write a test & get it fixed.
