### ISSUE TITLE
Abracadabra replaces system key binding

### ISSUE THREAD

**Issue by stevebeauge** [nicoespeon/abracadabra#817]
## Describe the bug

This extension shouldn't overrides the standard <kbd>CTRL</kbd> + <kbd>H</kbd> key-binding.

## How to reproduce

Press <kbd>CTRL</kbd> + <kbd>H</kbd> in a editor. It trigger the `@command:abracadabra.toggleHighlight`

## Expected behavior

Standard VS code's *replace* UI should open.

## Screenshots

![image](https://user-images.githubusercontent.com/184604/218985628-2ad3844d-c11f-4264-acec-b6c915c969dd.png).

I have no custom keybinding defined. This is the OOB VS Code + abracadabra setup

## Additional information

Working on Windows, where <kbd>CTRL</kbd> + <kbd>H</kbd> is the de-facto key shortcut for replacing text in nearly all text editors.

**Comment by nicoespeon** [comment]
Oh crap, I forgot to double-check this was an OK shortcut on Windows 🤦 

Yeah, that sucks. I'm changing that and shipping an updated version. New shortcuts will be:

| Feature               | Keybinding               | On Mac  |
| :-------------------- | :----------------------- | :------ |
| Toggle Highlight      | `Ctrl + Alt + H`         | `⌃ H`   |
| Refresh Highlights    | `Shift + Alt + H`        | `⌃ ⌥ H` |
| Remove All Highlights | `Ctrl + Shift + Alt + H` | `⇧ ⌃ H` |

@all-contributors please add stevebeauge for bugs 🙏

**Comment by stevebeauge** [comment]
That was quick!

Thanks!
