### ISSUE TITLE
convert to class based component to function based component is not working

### ISSUE THREAD

**Issue by sumit-pandey** [nicoespeon/abracadabra#83]
## Describe the bug

_A clear and concise description of what the bug is._

## How to reproduce

_Please detail steps to reproduce the behavior. Add code if necessary._

## Expected behavior

_Clear and concise description of what you expected to happen._

## Screenshots

_If applicable, add screenshots to help explain your problem._

## Additional information

- Version of the extension impacted: _vX.X.X_

_🧙‍ Add any other context about the problem here._

**Comment by David-Else** [comment]
@sumit-pandey Please fill in the information, you have left it all empty. At least copy/paste the code that is not working and explain what happens. Thanks.

**Comment by sumit-pandey** [comment]
//this class based component is not converting into functional based component using abracadabra 

import React, { Component } from "react";
import "./Search.css";
import PostsList from "./PostsList";
import MenuItems from "./MenuItems";

class Search extends Component {
  // runs after component is mounted
  state = {
    searchQuery: ""
  };
  handleInputChange = e => {
    this.setState({
      searchQuery: e.target.value
    });
  };

  render() {
    return (
      <div className="container">
        <div className="content">
          <h1 className="heading">Search</h1>
          <input
            type="text"
            id="search"
            placeholder="Insight, podcasts, or reports"
            value={this.state.searchQuery}
            onChange={this.handleInputChange}
          />
          {/* search list */}
          {this.state.searchQuery && (
            <div className="searchResults">
              <PostsList searchQuery={this.state.searchQuery} />
            </div>
          )}

          {/* top catagoreis */}

          <div
            className="top_categories"
            style={{ display: this.state.searchQuery ? "none" : "block" }}
          >
            <h6 style={{ fontSize: 16 }}>Top categories</h6>
            <div className="top_grids">
              <MenuItems />
            </div>

            {/* ----xxxxxxxxxx---- */}
          </div>
        </div>
      </div>
    );
  }
}
export default Search;

**Comment by nicoespeon** [comment]
Hi @sumit-pandey 👋 

Thanks for reporting. Indeed, this class component can't be refactored into a pure functional component, because it has a state.

Under the hood, it's [reactjs/react-codemod](https://github.com/reactjs/react-codemod) which does the conversion. If they can't handle it, Abracadabra won't propose the refactoring.

I'll suggest you raise the issue there to see if they could handle such pattern. If they do, we'll happily upgrade Abracadabra to make it work! Thanks!
