### ISSUE TITLE
Inline variable if ternary misses parens

### ISSUE THREAD

**Issue by xixixao** [nicoespeon/abracadabra#882]
## Describe the bug

Same issue like #816, but for ternary. Would be good to review the full list of expressions to see which ones need wrapping.

## How to reproduce

```ts
const style = commit.head === true ? chalk.red.underline : chalk.red;
sha = style(sha);
```

Try to inline `style`.

## Expected behavior

```ts
sha = (commit.head === true ? chalk.red.underline : chalk.red)(sha);
```

## Current behavior

Especially insidious because it's valid JS:

```ts
sha = commit.head === true ? chalk.red.underline : chalk.red(sha);
```

## Additional information

- Version of the extension impacted: latest as of writing

Applies at least to JS and TS

Thanks for this plugin!

**Comment by nicoespeon** [comment]
Good catch @xixixao. I'll have a tour of the different possible expressions and see if other ones would need wrapping 👍

**Comment by nicoespeon** [comment]
Note to self: inlining variables within mathematical operations can also be problematic if we don't put parens around.

```ts
const someValue = a + b
const result = someValue * 100

// Expected
const result = (a + b) * 100
```

**Comment by nicoespeon** [comment]
@all-contributors please add xixixao for bugs

**Comment by nicoespeon** [comment]
@xixixao thanks for the bug report. I was able to fix that and another pattern I thought about. 
If you find more, don't hesitate to open new issues 😉 That's very helpful!
