### ISSUE TITLE
JS and TS code without `;` is broken after refactoring

### ISSUE THREAD

**Issue by victor-homyakov** [nicoespeon/abracadabra#899]
## Describe the bug

Refactoring may move `return result` to the previous line when using code style without'; '. The resulting code is broken.

## How to reproduce

1. Create the JS file with the following code:
```js
const obj = {
	m1() {
		const result = Math.random()
		return result
	},
	m2() {
		if (Math.random() < 0.5) {
			// 1
		} else {
			// 2
		}
	}
}
```
2. Apply "Flip if/else" refactoring on `if (Math.random() < 0.5)`
3. Result:
```js
const obj = {
	m1() {
		const result = Math.random() return result
	},
	m2() {
		if (Math.random() >= 0.5) {
			// 2
		} else {
			// 1
		}
	}
}
```

## Expected behavior

```js
const obj = {
	m1() {
		const result = Math.random()
		return result
	},
	m2() {
		if (Math.random() >= 0.5) {
			// 2
		} else {
			// 1
		}
	}
}
```

## Screenshots

Video: https://github.com/nicoespeon/abracadabra/assets/121449/a175e57c-3d5e-4da4-94a3-e8fb27c2f952

## Additional information

- Version of the extension impacted: _v8.1.1_

**Comment by nicoespeon** [comment]
Thanks for reporting this @victor-homyakov, the code example made it easy to repro, identify, and fix the root cause. 

I'll make a release with the fix, so it stops messing up your code when executing the "Flip If/Else" refactoring (turns out it was specific to this one).

**Comment by nicoespeon** [comment]
@all-contributors please add victor-homyakov for bugs
