### ISSUE TITLE
Abracadabra extension causes performance issues with other extensions (prettier formatting, etc.)

### ISSUE THREAD

**Issue by dinofx** [nicoespeon/abracadabra#902]
I have prettier set as my formatter and format on save enabled.  If I:

1. open a large JS file, for example a bundle created by webpack with 50,000 lines, then
2. open a file with 15 lines of code
3. Add a few extra newlines to the end of the small file and save

I see a popup and the save is delayed for a long time.
![image](https://github.com/nicoespeon/abracadabra/assets/7581987/d63bbc72-13b8-423d-87ef-73ed8fc1a1ae)

If I disable this extension, the problem goes away.  I tried setting an ignore pattern to include the folder containing the large JS file, but I wasn't able to workaround the delay.

The problem has affected other extensions as well.  For example, I tried several extensions that simply display the absolute character offset.  When working in large files, these extensions would all display an initial offset but then would stop updating as the caret moved around.  Also I couldn't invoke the "go to offset" command for the extensions.

**Comment by maxxxxxdlp** [comment]
Seeing very bad performance when doing "Go to definition" in a large typescript definitions file (115k lines):

https://github.com/nicoespeon/abracadabra/assets/40512816/e741a4d0-a33d-4e33-a53d-2973b4c986bd

Using VS Code's [extension bisect](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect), found that Abracadabra is the cause - when it is disabled, performance in the 115k line file is awesome

**Comment by nicoespeon** [comment]
Thanks for reporting. To be honest, I'm not surprised. I didn't have perfs in mind when I started implementing these refactorings. 

It was working fine on files of reasonable size at first. The more refactorings we added to the catalog, the worse the perfs went, especially on large files. The exclusion feature was supposed to help, but it doesn't seem to.

We have had other obvious instances of this (see https://github.com/nicoespeon/abracadabra/issues/416) and I believe something like https://github.com/nicoespeon/abracadabra/issues/836 would be the solution. I haven't taken the time to dig into it, but I will think about it. In the meantime, https://marketplace.visualstudio.com/items?itemName=p42ai.refactor may be a better alternative so you have a catalog of refactorings, but with better perfs (I think).

**Comment by nicoespeon** [comment]
@dinofx that's a great idea!

I just shipped a release that contains a new setting `abracadabra.maxFileLinesCount` which should do that: don't evaluate refactorings based on the size of the file. It's configurable, but I put a 10,000 LOC default. If you can give it a try, let me know if that resolves your issue with the large bundles 🤞 

I also made changes that reduced the bundle size quite a lot for the latest release. I think that should also help: https://github.com/nicoespeon/abracadabra/pull/934

**Comment by j4k0xb** [comment]
> The goal is to reduce the impact on performance when you have a large file (eg. a bundle) in your codebase.

I'm frequently opening large bundles but the issue is that they're minified and thus 1 line
How about a size limit (e.g. in kb/mb) instead of lines?

**Comment by nicoespeon** [comment]
The new option `abracadabra.getMaxFileSizeKb` should help with that. IMO, we now have plenty of options and sensible defaults that should address this. 

However, feel free to re-open if you still experience bad performances because of Abracadabra.
