### ISSUE TITLE
Can't move class to an existing file

### ISSUE THREAD

**Issue by timbicker** [nicoespeon/abracadabra#915]
## Describe the bug

When I want to move a class to an existing file I get the error: 
I didn't find the code to move from current selection 🤔

I tried selecting the whole class, and only the name. Both don't work.

With functions it works.

**Comment by nicoespeon** [comment]
Hey @timbicker 👋 

Thanks for reporting. Moving classes to existing files wasn't supported yet indeed. However, I'm not gonna implement it. It looks like the TypeScript team has implemented the "Move to file" refactoring recently. It's available in VS Code and works like a charm, even with classes!

![vscode](https://github.com/nicoespeon/abracadabra/assets/1094774/5b4d8072-f0de-4e96-a3c8-a177dd54de3d)

I will drop the "Move to existing file" refactoring and encourage people to use the native one instead. Yay!

**Comment by nicoespeon** [comment]
Note: this was introduced with TS 5.2 https://code.visualstudio.com/updates/v1_82#_typescript-52

I have removed the refactoring in https://github.com/nicoespeon/abracadabra/commit/31cdad520cc87bcb57c635e7ba550b3ebf95a2cd
