### ISSUE TITLE
Make "Convert for to forEach" handle for…of loops

### ISSUE THREAD

**Issue by bennidi** [nicoespeon/abracadabra#92]
The for loop to foreach refactoring apparently does not work on `for (const entry of entries)` style loops. At least the plugin says it did not detect a valid for-loop.
Would be great to make it work for this style of loops.

Abracadabra version: 3.2.3

**Comment by nicoespeon** [comment]
Indeed, that would be doable. And I think that's something contributors could help with, it's not that complex.

## Code example

So this code:

```js
const array1 = ['a', 'b', 'c'];

for (const element of array1) {
  console.log(element);
}
```

Should be convertable to this code:

```js
const object1 = { 'a': 1, 'b': 2, 'c': 3 };

array1.forEach((element) => {
  console.log(element);
})
```

## Where to do the change

The refactoring already exist, everything is here: https://github.com/nicoespeon/abracadabra/tree/master/src/refactorings/convert-for-to-foreach

What you need to do:
1. Create at least one new test case to illustrate that it doesn't work today: https://github.com/nicoespeon/abracadabra/blob/61099010fe02a80a2428333f252a82184201a5b3/src/refactorings/convert-for-to-foreach/convert-for-to-foreach.test.ts#L156-L164
2. Make it work!

## Warning, edge-cases

Actually, `for…of` is something that can be used on any Iterable, not just Arrays: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Instructions/for...of

Another example of natural iterables are Strings. If we don't pay attention, we can break the code:

```js
const iterable = 'boo';

// This works!
for (const value of iterable) {
  console.log(value);
}

// This doesn't, `String.prototype.forEach()` doesn't exist
iterable.forEach((value) => {
  console.log(value);
});
```

Check MDN documentation for all existing iterables and make sure that we handle them properly. It's acceptable to not perform the refactoring for the non-supported iterables. 

But we shouldn't make it possible to break the code 😉

**Comment by filiphoeven** [comment]
I was actually looking for an automatic refactoring of "forEach" into "for (... of ...)" because "forEach" can be dangerous (doing something else than expected) when used with promises (or async/await) while "for of" works fine.

**Comment by ajanian** [comment]
I'm thinking about fixing this one as a good first issue.  @nicoespeon, I assume since it isn't assigned that it isn't being actively worked?  Just want to make sure I don't do work someone else is already doing.

**Comment by nicoespeon** [comment]
@ajanian indeed, no-one in working on that (or I'm not aware). If you start working on that let me know and I'll "assign" it to you so it clarifies it's in progress indeed.

Thanks for your help by the way, that's awesome 😃

**Comment by nicoespeon** [comment]
This will be available in the next release. I'll make it happen before the end of the week ;-)
