### ISSUE TITLE
Move to new file: configure case of the new filename

### ISSUE THREAD

**Issue by evanliomain** [nicoespeon/abracadabra#924]
## Describe what's missing

The refacto "Move to new file" should create a file with a case that match your project naming convention.

That a real painpoint: my project has, for example, kebab-case convention for filename. Each time I trigger this refactor, I must change case of the file.

## How would it work

Add some configuration for the extension to configure project filename case ("kebab-case", "camelCase", "PascalCase", etc).
In a source code file, add a function definition. Refactor it with "Move to new file".

## Expected behavior

It should create a file with the name of the function, with the case specified in configuration.

## Example
configuration: "kebab-case"

source code:
```
// is-odd.ts
export function isOdd(a: number): boolean {
  return !isEven(a);
}

function isEven(a:number): boolean {
  return 0 === a % 2;
}
```

Refactor `isEven` to "Move to new file". It create the file "is-even.ts" :
```
// is-even.ts
export function isEvent(a:number): boolean {
  return 0 === a % 2;
}
```

**Comment by nicoespeon** [comment]
Hey, @evanliomain, and thanks for raising it!

However, the "Move to a new file" refactoring isn't from Abracadabra. It's native to VS Code. It's coming from the embedded TypeScript.

Specifically, it's implemented here: https://github.com/microsoft/TypeScript/blob/main/src/services/refactors/moveToNewFile.ts

Abracadabra's refactorings are suffixed with ✨ so you can tell the difference with other sources:

![refactorings](https://github.com/nicoespeon/abracadabra/assets/1094774/d11e7da2-e032-470f-b4db-2be0fb075342)

--

I would then recommend creating this issue on the Typescript repository. In particular, it seems that they take the symbol name as the file name (https://github.com/microsoft/TypeScript/blob/aef4e468d9bd3a443c92b2d293432b8c82c73e98/src/services/refactors/moveToFile.ts#L1073), which is a reasonable default but they could provide an option for the casing, or prompt the user to ask for a file name before creating it.

Hope that helps!

**Comment by nicoespeon** [comment]
Note: with TS 5.2, there is a new "Move to file" that even allows you to create a new file and give it a name. I wonder if they would eventually get rid of "Move to a new file" in favor of this one

https://code.visualstudio.com/updates/v1_82#_typescript-52

![demo](https://github.com/nicoespeon/abracadabra/assets/1094774/f6de2049-f2ae-4a67-ac5a-30adf54b400a)
