### ISSUE TITLE
New Refactoring: Convert Switch to If/Else

### ISSUE THREAD

**Issue by delaaxe** [nicoespeon/abracadabra#93]
This would help me and others a lot. Would it be complex to implement, assuming we already have if/else to switch?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoespeon** [comment]
Sure, that will be a good idea indeed. So it's easy to go back and forth between the 2 patterns 👍 

We need to [create a new refactoring](https://github.com/nicoespeon/abracadabra/blob/master/CONTRIBUTING.md#create-a-new-refactoring) named `convertSwitchToIfElse`.

Then implement it, using tests to guide the progression. I'm not sure how complex it would be, but tests are really helpful to implement refactorings step by step. I'm sure we can get a basic scenario working pretty quickly 👍 

I'd put this one as a "Good First Contribution" if anyone wants to take a stab at it. Read [the CONTRIBUTING guide](https://github.com/nicoespeon/abracadabra/blob/master/CONTRIBUTING.md#create-a-new-refactoring), ask questions and open a draft PR if you need help!

**Comment by nicoespeon** [comment]
Released in [v4.2.0](https://github.com/nicoespeon/abracadabra/releases/tag/4.2.0) 🎉
