### ISSUE TITLE
Upgrade babel/traverse ti eliminate vulnerability.

### ISSUE THREAD

**Issue by Bruswei** [nicoespeon/abracadabra#946]
## Is this request related to a problem? Please describe.

Upon cloning the repository a vulnerability was found due babel/traverse version 7.20.12. 

## Describe the solution you'd like

Please upgrade @babel/traverse@7.20.12 to @babel/traverse@7.23.2 to fix the problem.

## Additional context

Not every vulnerability may pose an immediate risk to a Visual Studio Code extensions. Since the vulnerability only require an update of babel/traverse, I think this should be prioritized.

**Comment by nicoespeon** [comment]
Thanks for the report, this was fixed with https://github.com/nicoespeon/abracadabra/pull/948 👍
