### ISSUE TITLE
Use selection for "Add braces to if statement"

### ISSUE THREAD

**Issue by canadaduane** [nicoespeon/abracadabra#99]
## Describe what's missing

Currently, when you choose "Add braces to if statement" it works with a single line; however, it's often the case that multiple lines need to be added to an if statement.

## How would it work

Say I have three lines that are not yet part of an if statement (S1):

```
let ok
ok = someFunc()
callAnotherFunc(ok)
```

I've started typing an if statement (S2):
```
if (condition === 'true')
let ok
ok = someFunc()
callAnotherFunc(ok)
```

And now I'd like to make all three lines part of an if statement block (S3):
```
if (condition === 'true') {
  let ok
  ok = someFunc()
  callAnotherFunc(ok)
}
```

## Expected behavior

I'd like to be able to highlight the three lines above (in S2), and then choose "Add braces to if statement" and have it result in S3.

## Additional information

Version of the extension used: 4.1.0

**Comment by nicoespeon** [comment]
That's a nice suggestion, thank you @canadaduane 👍

**Comment by nicoespeon** [comment]
Hey @canadaduane!

So, I give this deeper thoughts and while it seems interesting when you're in the spirit of wrapping statements inside an if, it causes problems that I want to keep out of this extension scope.

In short, that's not a "refactoring". 

```js
if (condition === 'true') {
  let ok
  ok = someFunc()
  callAnotherFunc(ok)
}
```

and 

```js
if (condition === 'true') {
  let ok
  ok = someFunc()
  callAnotherFunc(ok)
}
```

are not the same thing. My goal for Abracadabra is to propose automated refactorings that you can use safely. If we fail to do so, I'd consider this a bug that should be fixed.

I can definitely see that if I select multiple lines, I explicitly want to wrap them inside the leading if statement. But when I do so, I'm effectively changing what the code does and would expect existing passing tests to fail (or failing tests to pass).

Therefore, I think that should be implemented in a different extension that would have a different goal. I created [hocus-pocus](https://github.com/nicoespeon/hocus-pocus) for similar reasons, but this one focuses on creating code that doesn't exist, based on the intention to create it. I feel what we're talking about is yet another kind of operations to make developer life more convenient. But I don't have one in mind at the moment.

Any way, thanks for suggesting. I think the idea is interesting for the developer. But I don't think it should be in Abracadabra.
