### ISSUE TITLE
Convert to Arrow Function: Does not work with a `export default function`

### ISSUE THREAD

**Issue by waltergalvao** [nicoespeon/abracadabra#993]
## Describe the bug

Trying `Convert to Arrow Function` throws an error when trying to convert a default function.

## How to reproduce

Try to run `Convert to Arrow Function` in the snippet below:

```ts
export default function MyFunction() {

}
```
## Expected behavior

- It should be able to convert it

## Screenshots

![Screenshot 2024-02-23 at 8 44 42 PM](https://github.com/nicoespeon/abracadabra/assets/1367578/580347ec-ad14-437a-b007-9b98688b2126)

## Additional information

- Removing the `default` keyword makes it work.

**Comment by nicoespeon** [comment]
Great catch @waltergalvao, thanks for the detailed report. I have fixed that and will create a new release to ship the fix 😉

**Comment by nicoespeon** [comment]
@all-contributors please add waltergalvao for bugs

**Comment by waltergalvao** [comment]
Thanks @nicoespeon - I missed the notifications, just saw this was quickly addressed. Great job!
